### ISSUE TITLE
Unpowered Rails do not become Powered Rails when powered

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#102]
Found at: https://code-dot-org.github.io/craft/

Giving power to an Unpowered Rail does not seem to convert it from Unpowered to Powered. The Redstone bits in the Unpowered Rail do not light up as they do in their Minecraft counterpart.

Steps:
1.  Place a Unpowered Rail into the gameworld
2. Hook up a Redstone Wire to the Unpowered Rail and the Pressure Plate
3. Step on the Pressure Plate
4. Observe Rail

Attachments:
[HoC_UnpoweredRails_Powered_DontConvertOrLightUp.zip](https://github.com/code-dot-org/craft/files/1297613/HoC_UnpoweredRails_Powered_DontConvertOrLightUp.zip)

**Comment by joshlory** [comment]
Nice find!

**Comment by Hamms** [comment]
Fixed by https://github.com/code-dot-org/craft/pull/378
