### ISSUE TITLE
Do not forget deactivatePiston() during clean up

### ISSUE THREAD

**Issue by WilliamHarmonMS** [code-dot-org/craft#110]
LevelPlane.deactivatePiston() explicitly defines directions because getOrthogonalPositions() does not return positions in the same order that FacindDirections{} expects them.

This is silly and needs to be fixed later. Will likely require refactoring any uses of getOrthogonalPositions() within the view, model or plane.

**Comment by joshlory** [comment]
@WilliamHarmonMS do we still need this tracking issue?

**Comment by WilliamHarmonMS** [comment]
No I don't think so... I think this has been addressed 👍
