### ISSUE TITLE
Pistons extend even if Steve/Agent is blocking

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#117]
Found at: https://code-dot-org.github.io/craft/

Steve/Agent is standing in-between a piston and a block. Powering the piston does not cause the piston to not fire (as the space is blocked by Steve/Agent and cannot be pushed out due to the block after them). Instead the animation pushes through Steve/Agent as if they were not there.

Steps:

1. Place piston on ground
2. Place unmovable block a block away from the piston head
3. Put Steve or Agent inbetween unmoveable block and piston head
4. Power the Piston
5. Observe piston head extension

Attachments:
[HoC_Agent_InPiston_ExtendsWhenPowered.zip](https://github.com/code-dot-org/craft/files/1316116/HoC_Agent_InPiston_ExtendsWhenPowered.zip)

**Comment by WilliamHarmonMS** [comment]
Do we know how we want this to work? In actual minecraft, the pistons do activate, but they push the player and agent into the next index (unless the next index is occupied, in which case the piston arm model and player/agent model overlap).

Having the piston arm extend, but allow the player to move out of the index (but then not back in) would be the most minecraft-y solution, but I am concerned that the visuals are not very nice. Need to get Cole and Joel together on this one to work something out.
