### ISSUE TITLE
Brown bonk lines remain displayed for Agent if colliding downwards

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#122]
Found at: https://code-dot-org.github.io/craft/

When moving the Agent downwards in a wall, brown "bonk" lines appear near the head of the Agent to animate that they have collided with a wall. However, unless like other directions, these lines remain displayed after the animation completes.

Steps:
1. Place any block on the ground (e.g. Grass)
2. Move the Agent one block above the placed block
3. Walk the Agent into the block
4. Observe animation

Attachments:
[HoC_Agent_WalkIntoBlockDownwards_BoinkLinesRemainDisplayed.zip](https://github.com/code-dot-org/craft/files/1318887/HoC_Agent_WalkIntoBlockDownwards_BoinkLinesRemainDisplayed.zip)

![hoc_agent_walkintoblockdownwards_boinklinesremaindisplayed mp4](https://user-images.githubusercontent.com/413693/31199130-4d60280a-a90b-11e7-92d3-36ce6753bbf8.gif)

**Comment by joshlory** [comment]
I think @WilliamHarmonMS has a fix for this?

**Comment by WilliamHarmonMS** [comment]
Yes, this is fixed in my current branch. Will be pushing a PR soon and will close this issue when it's merged. 👍

**Comment by WilliamHarmonMS** [comment]
This was merged in PR#229 with the new agent sprites.
