### ISSUE TITLE
[CRASH] Breaking block while Redstone is powered may cause lockup/crash

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#123]
Found at: https://code-dot-org.github.io/craft/

With a Redstone Wire powered (glowing red), a player attempts to break any block on the gameboard (including the powered Redstone Wire). After completing the cracking animation, App locks up (possibly crashes?) without showing the item drop animation.

Please note that this lockup only seems to occur if there are many items being powered by Redstone. 100% if at least 4 are, dropping to about 50% if 2-3 are powered, to 0% (doesnt happen) with just 1 powered.

Steps:
1. Place Pressure Plate
2. Place several Redstone affected items (e.g Iron Door, Piston, etc.)
3. Place Redstone Wire connecting them to the Pressure Plate
3. Stand Steve/Agent on the Pressure Plate
4. Destroy any block
5. Observe lockup/crash

Attachments:
[CRASH_HoC_PoweredRedstoneWire_BreakWhilePowered.zip](https://github.com/code-dot-org/craft/files/1318903/CRASH_HoC_PoweredRedstoneWire_BreakWhilePowered.zip)

**Comment by WilliamHarmonMS** [comment]
Fix here: https://github.com/code-dot-org/craft/pull/124
