### ISSUE TITLE
Placing block next to tree trunk causes duplicate leaves to appear

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#131]
Found at: https://code-dot-org.github.io/craft/

Place a block adjacent to a tree causes an extra set of leaves to appear. The leaves (or snow covered leaves in snowy biomes) after the block appears seem to grow darker (as the sprites are overlayed). Destroying the tree trunk seems to removes one set, but then leaves the duplicate behind.

Steps:
1. (Place or) Find a tree
2. Place a block next to the tree (not diagonally)
3. Observe leaves
4. Punch out the tree trunk
5. Observe leftover leaves

Attachments:
[HoC_Trees_PlaceBlockNext_DupeLeavesAppear.zip](https://github.com/code-dot-org/craft/files/1330442/HoC_Trees_PlaceBlockNext_DupeLeavesAppear.zip)

**Comment by joshlory** [comment]
@WilliamHarmonMS my guess is that we're not cleaning up old tree foliage sprites when we redraw redstone changes.

**Comment by WilliamHarmonMS** [comment]
@joshlory  I -swear- I updated the refreshActionPlane() to ignore trees... At the very least I knew this was a thing at some point. Bah. This will be a quick fix. 👍

**Comment by joshlory** [comment]
![tree-shadow](https://user-images.githubusercontent.com/413693/31154103-ac8026a8-a859-11e7-839f-e050420f81d0.gif)

**Comment by WilliamHarmonMS** [comment]
Yeah, it's refreshing the log, which calls the whole "createTree()" function again. I swear I saw this and fixed it once before, and I must have just scrapped the branch I was working on because it was for a different feature.
