### ISSUE TITLE
Using the Agent causes it to be knocked back a block

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#132]
Found at: https://code-dot-org.github.io/craft/

Walking up to an Agent and pressing [SPACEBAR] (to use it), cause the Agent to be pushed back a block.

Steps:
1. Walk up to the Agent
2. "Use" the Agent (Press [SPACEBAR])
3. Observe knockback

Attachments:
[HoC_Agent_Use_Knockedback.zip](https://github.com/code-dot-org/craft/files/1331131/HoC_Agent_Use_Knockedback.zip)

![hoc_agent_use_knockedback mp4](https://user-images.githubusercontent.com/413693/31199022-ff064626-a90a-11e7-810e-138cb9f3e1ed.gif)

**Comment by joshlory** [comment]
Looks like this is fixed with PR https://github.com/code-dot-org/craft/pull/241!
