### ISSUE TITLE
[CRASH] Destroying a Snow block causes lockup/crash

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#137]
Found at: https://code-dot-org.github.io/craft/

A player during gameplay comes across a Snow block and attempts to break break it. This causes the cracking animation and the particle explosion effect to occur. However, in the middle of the explosion affect, the game appears to lock up (possibly crash?).

Note, due to the white nature of a bunch of blocks (snow, quartz, etc.) we are not 100% certain that this is a Snow block. However, due to the snow biome it is in, we are making this assumption.

Steps:
1. Place Snow block
2. Destory the placed Rail
3. Observe lockup/crash

Attachments:
None. Map updated before video and callstack could be grabbed. Should be similar to Rail issue in #126.

**Comment by v-samtha** [comment]
Still occurs in both the playground (https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10) and Level 10 (https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10)

This is keeping players from completing Level 10.

**Comment by WilliamHarmonMS** [comment]
Reopening via Sam's comment
