### ISSUE TITLE
Redstone wire not popped when pushed directly by Piston head

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#143]
Found at: https://code-dot-org.github.io/craft/

A player sets up a situation where a Redstone wire is flush with a Piston head. Giving power to the Piston head, the head vanishes instead of popping the Redstone off its block. Note, if a block is pushed into the Redstone wire, the Redstone correctly pops off. It seems that only if the Redstone is flush with the Piston head does the error occur.

Steps:
1. Place a Piston
2. Place a Redstone wire at the head of the Piston
3. Power the Piston
4. Observe Piston head and Redstone wire

Attachments:
[HoC_Piston_PushingFlushRedstone_HeadDisappears.zip](https://github.com/code-dot-org/craft/files/1338902/HoC_Piston_PushingFlushRedstone_HeadDisappears.zip)

![hoc_piston_pushingflushredstone_headdisappears mp4](https://user-images.githubusercontent.com/413693/31195836-65c48aae-a900-11e7-8b14-371900e988eb.gif)

**Comment by Hamms** [comment]
This was fixed by https://github.com/code-dot-org/craft/pull/128
