### ISSUE TITLE
Rails that are already placed don’t get “rewired” correctly when a rail is placed downstream

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/craft#156]
For example, see puzzle 10 in script
Repro steps: 

1. Go to the puzzle above.
2. Break the wool and place a rail where it was
3. Observe that the nearest neighboring rails "reroute", but the first rail in the upper left does not.

**Comment by joshlory** [comment]
Can you share screenshots or a screen capture of the bug?

**Comment by ryansloan** [comment]
Can no longer repro
