### ISSUE TITLE
Iron doors can only face down

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/craft#157]
It looks bad if they are supposed to be facing left/right, because it still points downward. Presumably we need different assets here if we want to support this scenario, like in Puzzle 4

**Comment by WilliamHarmonMS** [comment]
I just took a look at level 4 and don't see an iron door? There should not be any iron doors that are east-west accessible (also users cannot place them) for this very reason. Given the static perspective of the camera, Joel decided that east-west doors would look bad in general and veto'd their inclusion. I can follow up with him to confirm this though.

**Comment by ryansloan** [comment]
It's not there because it got removed (since it looked bad). We can leave the doors out, but we need input from Cole because the opening he designed for the door was moving left-right

**Comment by WilliamHarmonMS** [comment]
Roger that, will confirm with Cole about the design. 👍

**Comment by ryansloan** [comment]
It looks like it's been changed to a piston, closing this out.
