### ISSUE TITLE
Rails incorrectly rotated when pushed by a Piston

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#158]
Found at: https://code-dot-org.github.io/craft/

Using a Piston, a player pushes a Rail. If the Rail is just a single block (and not connected to any other rails), the Piston will push it and then rotate it incorrectly 90 degress (see Video 1). If the Rail is connected to only 1 other Rail that is NOT in line with the direction the Piston is pushing, that Rail piece will transform into a turn piece (see Video 2).

It only seems to correctly push (without rotation or transformation) if the Rails are in line with the Piston head OR the the Rail is 3+ blocks long perpendicular with the Rail head.

Steps:
1. Place (or Find) a Piston
2. Place a Rail in front of the Piston head
3. Power the Piston
4. Observe Rail rotation

Attachments:
[HoC_Piston_PushRail_IncorrectRotation1.zip](https://github.com/code-dot-org/craft/files/1345267/HoC_Piston_PushRail_IncorrectRotation1.zip)
[HoC_Piston_PushRail_IncorrectRotation2.zip](https://github.com/code-dot-org/craft/files/1345268/HoC_Piston_PushRail_IncorrectRotation2.zip)

**Comment by alalb** [comment]
Based on the current level design, this situation is impossible. Talked to Design about this and we are ok to close it.
