### ISSUE TITLE
Level 6 How-To description contains incorrect information

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#166]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/6

The How-To description for Level 6 contains information about the Agent needing to get to the pressure plate to open the back door. However, a pressure plate is nowhere to be found in the level.

Steps:
1. Load Level 6
2. Read How-To description
3. Observe level layout

Attachments:
![hoc_level6_incorrectdescription](https://user-images.githubusercontent.com/31709758/31098717-67fa9d24-a778-11e7-8a9d-4dc259705dc7.jpg)

**Comment by kiki-lee** [comment]
Fixed
