### ISSUE TITLE
[HARDLOCK] Giving Repeat loops an extremely large number causes website to lock up

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#167]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/2

In any level utilizing a Repeat loop, a mishcievious kid gives the Repeat value a very large number (think millions, there doesn't seem to be a limit). After plugging in other block commands, the user then attempts to run it by pressing the Run command. This causes the website to seize up and stop responding.

Note, previous iterations seem to have limited this command to a dropdown selection of values between 2 to 10. Thus, circumventing the hardlock/issue.

Steps:
1. Load a level with a Repeat loop (e.g. Level 2)
2. Utilize a Repeat loop in the code
3. Give that Repeat loop a large value (e.g. 10000000000000)
4. Select Run to run the Repeat loop
5. Observe website functionality

Attachments:
[HoC_RepeatLoop_LargeValue_WebsiteHangs.zip](https://github.com/code-dot-org/craft/files/1350393/HoC_RepeatLoop_LargeValue_WebsiteHangs.zip)

**Comment by ryansloan** [comment]
Won't fix.
