### ISSUE TITLE
No How-To description in Level 9

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#170]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/9

The How-To description appears to be missing for Level 9 as no text appears when starting (or restarting) the level.

Steps:
1. Load Level 9
2. Look for How-To description or text

Attachments:
![hoc_level9_nohowtodescription](https://user-images.githubusercontent.com/31709758/31101147-3ff917ac-a781-11e7-8db6-9c0a7909a513.jpg)

**Comment by kiki-lee** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10120168-17969280_8-s1-v1.png?transparent=1&palette=1&width=246)
