### ISSUE TITLE
No Code Blocks are available for use in Level 9

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#171]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/9

The Code Blocks (that are usually found between the gameboard and workspace) appear to be missing for Level 9 as the section appears to be missing and thus making it impossible to complete the level.

Steps:
1. Load Level 9
2. Look for Code Blocks section

Attachments:
![hoc_level9_nohowtodescription](https://user-images.githubusercontent.com/31709758/31101147-3ff917ac-a781-11e7-8db6-9c0a7909a513.jpg)

**Comment by kiki-lee** [comment]
Fixed
