### ISSUE TITLE
Popup for Pressure Plates in Level 1 doesn't correctly point to the Pressure Plate

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#178]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1

On launching Level 1 for the first time, a special pop-up will appear informing the player what a Pressure Plate is. However, this pop-up doesn't seem to correctly point to the Pressure Plate on the game board. At first, it will be half off the screen and unreadable. If the player resizes the window, it will try to correct itself to be readable, but is still not correctly pointing to the Pressure Plate. (See attached video)

Note, subsequent launches of Level 1 will not get this pop-up to appear again. Clearing out the web browser cache seems to do the trick and causes it to appear again.

Steps:
1. (If necessary) Clear browsing cache from web browser
2. Load Level 1
3. Select a Character
4. Accept How-To description
5. Observe pop-up message for Pressure Plates

Attachments:
[HoC_Level1_PressurePlatePopUp_NotPositionedCorrectly.zip](https://github.com/code-dot-org/craft/files/1353372/HoC_Level1_PressurePlatePopUp_NotPositionedCorrectly.zip)

**Comment by kiki-lee** [comment]
Fixed
