### ISSUE TITLE
How-To for Level 1 does not explain how to perform Use action

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#179]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1

Reading through the How-To for Level 1, players are told to use the Arrow Keys to get to the Pressure Plate to complete the level. However, in order to reach the Pressure Plate, they have to pass through a Wooden Door that needs to be Used in order to open it. The explanation on how to do this (pressing [SPACEBAR] or [LEFT-CLICK] on the gameboard is not given.

There also isn't a button for Use underneath the gameboard (as there is for the movement Arrow buttons)

Steps:
1. Load Level 1
2. Select a character
3. Read the How-To description
4. Observe lack of explanation for the "Use" button/command

Attachments:
![hoc_level1_howto_needstoexplainuse](https://user-images.githubusercontent.com/31709758/31141806-40e118de-a82d-11e7-9564-2c3b0ce5a360.jpg)

**Comment by kiki-lee** [comment]
There was no door when the instructions were added. I'll update.

**Comment by kiki-lee** [comment]
Fixed
