### ISSUE TITLE
No Helpful Hint is displayed when failing any levels

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#180]
*Bug has been updated to reflect that no levels have any Helpful hints on failure*

Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1

After failing to successfully complete a Level, a Helpful Hint usually appears under the How-To description to given guidance for players who may be struggling with a level. However, an empty dialogue box appears instead for all levels

Steps:
1. Load any level
2. Close all pop up dialogue boxes
3. Select "Run"
4. Let time expire (fail level)
5. Observe Helpful Hint that appears (or lack thereof)

Attachments:
![hoc_level1_nohelpfulhint](https://user-images.githubusercontent.com/31709758/31142208-6f02f33a-a82e-11e7-8ef7-bc4b20764a76.jpg)

**Comment by v-samtha** [comment]
Updated to reflect that no levels have any Helpful hints on failure and not just Level 1

**Comment by kiki-lee** [comment]
I don't believe curriculum can provide failure hints.

**Comment by joshlory** [comment]
+cc @Hamms is this something that needs to be done on the engineering side?

**Comment by Hamms** [comment]
On the engineering/product side, we should probably add a default, "catch-all" failure message for when no override is provided. But @kiki-lee, previous years have used the failure message override setting extensively for this. (annoyingly, they did it outside the context of levelbuilder, but that's still what was used)

**Comment by Hamms** [comment]
oh, my mistake; after looking a bit closer it looks like we're actually using the `appSpecificFailError` override, which is not exposed in levelbuilder; I can update it to be so.

**Comment by Hamms** [comment]
Although we could probably just use the standard failure message override instead, and that would likely make i18n easier. @kiki-lee, @joshlory, thoughts?

**Comment by ryansloan** [comment]
We should add the catch-all errors to the standard failure message override in each of the puzzles. I will take this task and send to @kiki-lee for review

**Comment by alalb** [comment]
Instructions and hints were updated.
