### ISSUE TITLE
Diamond sprite is not centered on top of Diamond Block

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#185]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1

For the Diamond Path objectives, a player needs to pick up a Diamond sprite (miniblock) on top of a Diamond Block found in each level. On level load, the Diamond sprite is dropped onto the Diamond Block. However, it seems to randomly pick a pixel on the Block to drop on instead of centering it. This can lead to situations where the players can snag the Diamond sprite without having to complete the objective.

Steps:
1. Load any level
2. Observe Diamond sprite location
3. Reload the level
4. Observe Diamond sprite location

Attachments:
[HoC_DiamondPlacement_RandomToPixelOnBlock.zip](https://github.com/code-dot-org/craft/files/1353853/HoC_DiamondPlacement_RandomToPixelOnBlock.zip)

**Comment by joshlory** [comment]
I _think_ think is by design, but tagging @Hamms to confirm.  My understanding is that we randomize the location of the drop, so stacked drops are each visible.

Maybe we should always place the first drop in the center of the square?
