### ISSUE TITLE
The lesser How-To description for Level 7 is incorrect

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#188]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/7

If a user selects the "Less" option for the  How-To for Level 7, the text describes needing to help the Agent to get to the Pressure Plate. However, there is no Pressure Plate on the gameboard and is not helpful for quickly telling the player to use a function to solve the level.

Steps:
1. Load Level 7
2. Select the Less button
3. Observe the smaller How-To description

Attachments:
![hoc_level7_smallhowto_incorrect](https://user-images.githubusercontent.com/31709758/31150657-5890972c-a849-11e7-9d60-f319ca916d2f.jpg)

**Comment by kiki-lee** [comment]
Fixed
