### ISSUE TITLE
"Secret Grove" referred to inconsistently in multiple levels

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#189]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/6

In the How-To descriptions for Levels 2, 3, 4 and 6, they make mention of a "Secret Grove" that the player is progressing toward, in and out of. However while Level 2 and 4 seem to refer to this area as "Secret Grove", Level 3 refers to it as "secret grove" (no caps) and Level 6 refers to it as "Secret Garden" (and not Grove).

Steps:
1. Load Level 2
2. Observe How-To text
3. Load Level 3
4. Observe How-To text
5. Load Level 4
6. Observe How-To text
7. Load Level 6
8. Observe How-To text

Attachments:
![hoc_secretgrove_inconsistantthroughoutlevels](https://user-images.githubusercontent.com/31709758/31151305-b9373a2a-a84b-11e7-8f9a-8fea8831951c.jpg)

**Comment by kiki-lee** [comment]
Fixed
