### ISSUE TITLE
Several levels are missing the Arrow buttons (for touch movement)

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#191]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/4

On Levels 4, 6, 7, 9 and 10, when the player presses the Run button, the corresponding Arrow buttons that allow the player to move Steve via Touch controls do not appear. These Touch only players are unable to successfully complete the levels.

Steps:
1. Load Level 4, 6, 7, 9 or 10
2. Press the Run button 
3. Observe lack of Arrow buttons

Attachments:
[HoC_Touch_ArrowButtons_MissingOnLevels4-6-7-9-10.zip](https://github.com/code-dot-org/craft/files/1354256/HoC_Touch_ArrowButtons_MissingOnLevels4-6-7-9-10.zip)

**Comment by joshlory** [comment]
Fixed!
