### ISSUE TITLE
Steve performs destroy block animation if Agent doesn't have valid target

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#192]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/7

While running its code, the Agent may encounter a situation where it is asked to destroy the block in front of it but there is no block to destroy. This causes Steve instead of the Agent to perform the swinging animation.

Steps:
1. Load any level with the Destroy Block code block (e.g. Level 7)
2. Snap the Destroy Block to the Run block
3. Select Run
4. Observe animations of Steve and Agent

Attachments:
[HoC_DestroyBlock_AgentInvalid_SteveSwingsInstead.zip](https://github.com/code-dot-org/craft/files/1354260/HoC_DestroyBlock_AgentInvalid_SteveSwingsInstead.zip)

**Comment by joshlory** [comment]
@Hamms I think this is fixed by PR https://github.com/code-dot-org/craft/pull/195?
