### ISSUE TITLE
Victory condition for Level 9 is missing (incorrect?)

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#200]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/9

After successfully stepping on the Pressure Plate to cause the Piston to destroy the Redstone Torch to cause the Sticky Piston to reveal the goal (yellow) block, the player maneuvers Steve to it. However, when Steve is standing on the block, the victory condition is not properly triggered.

Steps:
1. Load Level 9
2. Program the Agent to destroy the 3 impeding blocks
3. Run the code
4. Have Steve step on the Pressure Plate
5. Move Steve to the Yellow Block
6. Observe victory state

Attachments:
[HoC_Level9_VictoryCondition_Missing.zip](https://github.com/code-dot-org/craft/files/1356747/HoC_Level9_VictoryCondition_Missing.zip)

**Comment by alalb** [comment]
I updated the victory point for the level and it should work as expected now.

**Comment by WilliamHarmonMS** [comment]
This was an error in the level builder configuration. Resolved!
