### ISSUE TITLE
Level 10 cannot be completed

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#202]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10

Near the yellow (victory) block at the end of the level some Pistons and other Redstone items are placed. When the Agent destroys the first snow block in its path, an update is made causing the top Piston to extend. This causes the Redstone Torch to be kicked, but then does not cause the bottom piston to retract. Due to this, the yellow block cannot be reached and the level cannot be completed.

Steps:
1. Load Level 10
2. Program the Agent to punch out blocks and to place down Rails for Steve to travel on
3. Attempt to get Steve to that Victory block

Attachments:
[HoC_Level10_PistonsFireIncorrectly_UnableToBeCompleted.zip](https://github.com/code-dot-org/craft/files/1356854/HoC_Level10_PistonsFireIncorrectly_UnableToBeCompleted.zip)

**Comment by joshlory** [comment]
I think this is fixed now?  Assigning back to @v-samtha to verify & close out.

**Comment by v-samtha** [comment]
It is indeed fixed. Level 10 is able to be completed, but the level design is pending Cole's review and stamp of approval. I have a feeling that this level will change a bunch. The original issue has been fixed though. Closing as fixed.

**Comment by joshlory** [comment]
Thanks!
