### ISSUE TITLE
Several levels have excessive amounts of choices for Place Block

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#203]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/5

Starting with Level 4, players are introduced to the Place Block code block that allows the Agent to place a block into the gameboard. For Level 4, the number of selected blocks has been limited to a couple. However, for all the subsequent levels (5 - 10), a much larger list is provided to the player. Some of those options include Pistons (which should not be placeble at all) and House pieces (which can cause the App to crash). These options may need to be reduced (and probably themed with the level that they are in).

Steps:
1. Load Level 5
2. Open dropdown for Place Block
3. Observe selections presented
4. Repeat Steps 1 - 3 with each subsequent level

Attachments:
[HoC_Level10_PlaceBlock_LotsOfOptions.zip](https://github.com/code-dot-org/craft/files/1356883/HoC_Level10_PlaceBlock_LotsOfOptions.zip)

**Comment by kiki-lee** [comment]
Fixed
