### ISSUE TITLE
Function block appears twice in Level 10

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#204]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10

In the available Blocks list to the left of the Workspace, the "make segment" Function block appears twice.

Steps:
1. Load Level 10
2. Observe available blocks

Attachments:
![hoc_level10_functionblock_appearstwice](https://user-images.githubusercontent.com/31709758/31191771-1abb2da8-a8f4-11e7-97e6-da27069ab0b7.jpg)

**Comment by kiki-lee** [comment]
Fixed
