### ISSUE TITLE
How-To pop-up dialogue only appears for first two levels

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#208]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/3

When loading into a Level, a pop-up dialogue box appears typically displaying the How-To text for the level which can be dismissed by pressing OK. However, this pop-up box only appears for Levels 1 and 2. For the rest of the levels, the box does not appear and seems to be inconsistent with every other Minecraft level.

Steps:
1. Load Level 1 or 2
2. Observe How-To pop-up that appears
3. Load Level 3 (or any other subsequent level)
4. Observe lack of How-To pop up

Attachments:
[HoC_HowToPopUp_OnlyForLevels1And2.zip](https://github.com/code-dot-org/craft/files/1357396/HoC_HowToPopUp_OnlyForLevels1And2.zip)

**Comment by kiki-lee** [comment]
These are called "callouts".  We don't use them often, only when we think something will be overly confusing and not covered by instructions.  

We can take a callout pass when we do hints, after we get student feedback (or if anyone has specific concerns that a student won't know what/where something is.)

**Comment by joshlory** [comment]
Closing for now.  We can re-visit if the progression is too confusing in the classroom visit.
