### ISSUE TITLE
Victory animation (and level completion) interrupted on Redstone change

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#209]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/2

A player successfully navigates Steve to a victory block. During the victory animation (where the chime sfx plays and and they jump up and down), a Redstone change occurs. For example, in Level 2, the Agent standing on the Pressure Plate moves off of it while the animation is playing. This not only interrupts the victory animation, but the game does not progress to the level completion screen and causes Steve to become stuck (until reset)

Steps:
1. Load Level 2
2. Program the Agent to either Pressure Plate
3. Have the Agent idle (spin in place)
4. Navigate Steve to the victory block
5. During the animation, have the Agent move off the Pressure Plate (may take some coding tweaks)
6. Observe victory animation and level completion

Attachments:
[HoC_VictoryAnimation_InterruptedOnRedstoneChange.zip](https://github.com/code-dot-org/craft/files/1357552/HoC_VictoryAnimation_InterruptedOnRedstoneChange.zip)

**Comment by joshlory** [comment]
Tracking all animation interruption bugs under this issue.
