### ISSUE TITLE
All-time counter on Completion screen is not a summation

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#211]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/2

A player successfully completes a level and a Completion screen appears that gives the player some stats about their play session. Included in this info is an "All-time total" which counts the lines of code that the player has used to complete the levels. However, instead of the total being a summation of all the levels thus far (e.g. 3 on the 1st, 6 on the 2nd, and 8 on the 3rd for a total of 17 across 3 levels), it just cumulatively adds whatever number of lines were used in that level to a total. This can lead to situations where kids may try to add extraneous additions to boost their line count (which may be counterproductive)

Steps:

1. Load Level 2 in Incognito/InPrivate/Private mode
2. Program a simple two line method to get the Agent to the Pressure Plate
3. Run the Code and move Steve to the victory block
4. Observe victory screen and the "All-time total" counter value
5. Replay Level 2
6. Run the same code and move to Steve to the victory block
7. Observe victory screen and the new "All-time total" counter value

Attachments:
[HoC_LevelCompleteScreen_AllTimeCounter_CumulativeNotSummation.zip](https://github.com/code-dot-org/craft/files/1357656/HoC_LevelCompleteScreen_AllTimeCounter_CumulativeNotSummation.zip)

**Comment by joshlory** [comment]
Assigning @ryansloan to triage.

**Comment by ryansloan** [comment]
Won't fix - we have this issue across all our CS Fundamentals tutorials and courses, and in the long run we're moving away from presenting this metric in this way so we're not investing in improving it.
