### ISSUE TITLE
The first grid square of the minecart animation is skipped

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#212]
The cart should go straight and then turn, instead of sliding diagonally past the first corner:

![minecart-animation](https://user-images.githubusercontent.com/413693/31236655-96f4fb6e-a9a9-11e7-8a9f-cb40f55e4dca.gif)

**Comment by joshlory** [comment]
@WilliamHarmonMS can you take a look at this one?  I think it may be related to PR https://github.com/code-dot-org/craft/pull/146.

**Comment by WilliamHarmonMS** [comment]
@joshlory  Yeah absolutely. I think it's because it's starting the animation on the rail after the rail you 'use'. At least that's what it looks like. I can definitely look into it.

**Comment by WilliamHarmonMS** [comment]
This actually gets fixed by the current state of [PR#332](https://github.com/code-dot-org/craft/pull/332)

**Comment by WilliamHarmonMS** [comment]
332 was merged! so closing

**Comment by joshlory** [comment]
It looks like the original issue is fixed, but I'm still seeing a speed-up when hoping on a minecart from a corner rail:

![minecart-movement-skip](https://user-images.githubusercontent.com/413693/32394730-56dc1b94-c09b-11e7-8701-712da56c34f3.gif)

**Comment by ryansloan** [comment]
Won't fix.
