### ISSUE TITLE
Player's use of function blocks is limited to existing functions

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#214]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10)

On Level 10, the only function block available in the Blocks section is "make segment".  If the player drags the "make function" definition block from the Blocks section and into the Workspace to make "make segment2", the Blocks section is not updated with a "make segment2" function block.  Also, renaming the existing function "make segment" does not update the "make segment" function block in the Blocks section.  However, renaming the function does rename existing invocations in the Workspace.
Furthermore, reloading the page will return the renamed function to its original name and delete any new functions.

Repro Steps:
1. Load Level 10 (or any level with a provided function)
2. Drag the function definition block "make segment" from the Blocks area to the Workspace to make "make segment2"; provide an arbitrary definition
3. Drag the function block "make segment" from the Blocks area to the Workspace
4. Rename the function definition for "make segment" in the Workspace
5. Observe function call in Workspace and name of function block in Blocks area; check for existence of function blocks other than "make segment" in Blocks area 
6. Reload page

Actual result:
Only the function provided when the page is loaded is usable
Expected result:
User can create, define, call, and rename functions.

![functions](https://user-images.githubusercontent.com/26069359/31237706-90ec2258-a9ac-11e7-971f-52d7865006d8.png)

**Comment by alalb** [comment]
Fixed.
