### ISSUE TITLE
While standing on a pressure plate, bumping into an obstacle re-triggers the pressure plate

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#220]
Is this a bug, or expected behavior?

![pressure-plate-reset](https://user-images.githubusercontent.com/413693/31242940-901dded2-a9bd-11e7-9383-5c191a61e144.gif)

**Comment by WilliamHarmonMS** [comment]
I think it's a bug. Does it remain closed, or does it re-open? I think it's just because the door-close-because-leaving-index is done before we know if we bumped or not. 😩
