### ISSUE TITLE
A player attempting to place "quartzOre" into lava will cause a hang/crash to occur.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#222]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/8

Steps:
1) Launch hour of code level 8.
2) Apply the commands Move forward twice > then place "quartzOre" 
3) Run the simulation.

**Actual results:**
Hang/Crash occur when the agent attempts to place quartzOre in lava.

**Expected results:**
Agent can place quartzOre down in lava. Or quartzOre is removed from place command.

Note: the only way to continue working is to refresh the website. 

[quartzOreCrash.zip](https://github.com/code-dot-org/craft/files/1360401/quartzOreCrash.zip)

Callstack:
Uncaught TypeError: Cannot read property '0' of undefined
    at e.exports.e.createBlock (craft.min-3aeda0dc36bedc8416c37de5b414956cd7c5fb5a50e5ec347517b2721b50841c.js:12)
    at e.exports.e.refreshGroundPlane (craft.min-3aeda0dc36bedc8416c37de5b414956cd7c5fb5a50e5ec347517b2721b50841c.js:12)
    at e.exports.e.setBlockAt (craft.min-3aeda0dc36bedc8416c37de5b414956cd7c5fb5a50e5ec347517b2721b50841c.js:11)
    at e.exports.e.placeBlock (craft.min-3aeda0dc36bedc8416c37de5b414956cd7c5fb5a50e5ec347517b2721b50841c.js:10)
    at craft.min-3aeda0dc36bedc8416c37de5b414956cd7c5fb5a50e5ec347517b2721b50841c.js:2
    at craft.min-3aeda0dc36bedc8416c37de5b414956cd7c5fb5a50e5ec347517b2721b50841c.js:12
    at c.SignalBinding.execute (phaser.min-86cb81ba30b6548a6f477d373370222ff3e168bc38caf389bc065ec894437fc8.js:9)
    at c.Signal.dispatch (phaser.min-86cb81ba30b6548a6f477d373370222ff3e168bc38caf389bc065ec894437fc8.js:9)
    at c.Animation.complete (phaser.min-86cb81ba30b6548a6f477d373370222ff3e168bc38caf389bc065ec894437fc8.js:16)
    at c.Animation.update (phaser.min-86cb81ba30b6548a6f477d373370222ff3e168bc38caf389bc065ec894437fc8.js:16)

**Comment by alalb** [comment]
I removed "clayHardened" and "quartzOre" from the dropdown on  level 8 and 9

**Comment by joshlory** [comment]
Thanks @alalb!  Does this resolve the issue?

**Comment by v-jaarba** [comment]
The "Place" block no longer has the items in the list that caused this crash in any level. 
Checked levels 1-10 and no item in Place cause this crash to occur.

**Comment by joshlory** [comment]
Great!  Thank you @v-jaarba for the bug report and @alalb for the quick fix!

**Comment by v-jaarba** [comment]
Level 13 has the place QuartzOre option again and it is causing the crash to occur again.

**Comment by v-jaarba** [comment]
Attempting to place TopSnow On Water also causes this crash to occur.

**Comment by v-jaarba** [comment]
Building a list of all crash place items on each level

**Comment by v-jaarba** [comment]
After level changes items that cause this crash have snuck back in.
Level 13: quartzOre and topSnow,
Level 15: quartzOre.
Currently still in HoC that need to be removed.

**Comment by v-jaarba** [comment]
finding more items now with new update that cause crash, adding to list
all will cause a crash when attempting to put them down in water, or lava.
quartzOre, topSnow, deadbush, hardened clay, grassPath, netherBrick, snowyGrass, houseTopA, houseRightC, houseRightB, houseLeftA, houseRightA, houseBottomA, houseBottomB, houseBottomC,
houseBottomD,

**Comment by kiki-lee** [comment]
Do we want to handle this by disallowing those options, or by fixing the crash?

**Comment by Hamms** [comment]
Both, probably. I don't think we want to allow placing of _any_ of those listed blocks, but it still shouldn't crash if you try to do so.

**Comment by kiki-lee** [comment]
Even in freeplay?  

If that's the case, we should remove them from the pre-populator and after the levels are completed, I'll go through and remove any offending blocks that are left over.

**Comment by Hamms** [comment]
I think so, yeah; none of those are blocks that should normally be placeable, they're all either blocks that are only naturally-occuring, decoration blocks, or custom blocks only used by our app.

By "the pre-populator", do you mean the button in levelbuilder that populates the field with the JSON array, or something else?

**Comment by kiki-lee** [comment]
Yep, that one.  Although, most of the levels are already created, so that only helps us if we use this setup again in the future.

**Comment by kiki-lee** [comment]
Oh, we don't want to take out DeadBush, do we?

**Comment by kiki-lee** [comment]
Or grassPath?

**Comment by Hamms** [comment]
I think we do; those are decoration blocks, aren't they? Do we want to support placing decoration blocks?

**Comment by v-jaarba** [comment]
ali was able to remove all of the crash items from the freeplay level, but now all the crash blocks are in the new level 10, Should remove all but rail from place on this level.

**Comment by Hamms** [comment]
In general, levels should be presenting the player with a relatively focused subset of placeable blocks rather than always enabling all of them

**Comment by alalb** [comment]
I deleted the other items from the place on this level. 
@Hamms are there any Dev work left on this bug?

**Comment by Hamms** [comment]
Nope!

**Comment by v-jaarba** [comment]
@alalb Level 10 still has 2 items that hit this crash, Tree and Hardened Clay are still in the place block.
