### ISSUE TITLE
Inconsistant Z-Indexing - Steve placed under rails when Agent bumps into edge of map. 

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#228]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/13

Steve will be placed under the rails if the rail segment is vertical when the Agent runs into a wall and Steve is standing on that segment.

Steps:
1) Launch hour of code level 13.
2) Enter Code block: Repeat 10 times > place rail, move forward 
3) Hit the run button.
4) Move Steve onto the rails.
5) Observe once Agent bumps into wall.

Actual results:
Once the Agent bumps into the wall Steve’s Z-order is on the bottom of the rail.

Expected results:
Steve remains on top of Z-order.

Note: player can still move. Once Steve moves his z-order is fixed.
If the timer finishes Steve also is placed back on top.
If the rail is horizontal, then Steve is not placed under rail.

If Agent places vertical rail at Steve's location Steve will be placed under the rails.
Redstone wire/Redstone torch also does the same.

[Code.org [levelbuilder] - HoC 17 - Cole #13 - Google Chrome 10_5_2017 4_10_08 PM.zip](https://github.com/code-dot-org/craft/files/1361124/Code.org.levelbuilder.-.HoC.17.-.Cole.13.-.Google.Chrome.10_5_2017.4_10_08.PM.zip)

**Comment by Hamms** [comment]
I believe this should have been fixed by https://github.com/code-dot-org/craft/pull/279; @v-jaarba can you confirm that you no longer repro?

**Comment by v-jaarba** [comment]
This no longer occurs, It has been fixed.
