### ISSUE TITLE
Destroying block held by Stick Piston display wrong sprite in Level 9

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#231]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/9

Whenever both Steve and the Agent occupy the same block, the Agent is always rendered on top of Steve. After talking with William, it seems that the current plan is to have Steve always render on top of the Agent. However, a new sprite sheet is coming for the Agent which may change this.

Note, this issue does not seem to occur in Level 4

Steps:
1. Load Level 9
2. Write code to break the block for the Sticky Piston aimed down
3. Run code
4. Observe Sticky Piston 

Attachments:
[HoC_Level9_StickyPiston_SpriteIncorrect.zip](https://github.com/code-dot-org/craft/files/1361230/HoC_Level9_StickyPiston_SpriteIncorrect.zip)

**Comment by WilliamHarmonMS** [comment]
Was a level builder issue. Is not fixed as of 10/6
