### ISSUE TITLE
Function Name Length is not capped - Causing a loss of Workspace.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#232]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/13

This issue could cause someone who is trying to name functions literally to lose workspace area without knowing how to correct the issue.

Repro steps:
1)	Start Level 13.
2)	In the block selection area > rename the function with a long string of characters.
3)	Observe the workspace as the name of the function increases.

Actual Results:
The workspace is lost as the name of the function increases. 

Expected Results:
The workspace does not shrink on the size of the name of functions.

Note: The function can be renamed to return the workspace but if the fix is not known it can cause confusion.

Video
[Uploading Code.org [levelbuilder] - HoC 17 - Cole #13 - Google Chrome 10_5_2017 5_35_47 PM.zip…]()

**Comment by ryansloan** [comment]
Won't fix. We don't restrict function name length anywhere in the product.
