### ISSUE TITLE
Snapping command blocks together slowly cause them to drift off the Workspace

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#236]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/4

A player is figuring out how to complete a level and starts snapping code blocks together. Being terribly inefficient, the player snaps together a very large amount of blocks (20-30) trying to figure out the level. As these blocks get snapped together, they slowly curve to the left. If connected to the Run block, they can run off the Workspace.

Note, reloading the level seems to realign the blocks correctly. It appears that when snapping, the blocks aren't flush but are offset by a pixel or two. This, over time, causes the blocks to wander off the board.

Steps:
1. Load any level with multiple command blocks
2. Snap an excessive amount of blocks to the Run block
3. Observe the slow curve off the Workspace

Attachments:
[HoC_CommandBlocks_SnapToRun_WanderOffWorkspace.zip](https://github.com/code-dot-org/craft/files/1363499/HoC_CommandBlocks_SnapToRun_WanderOffWorkspace.zip)

**Comment by joshlory** [comment]
Very weird!  It repros on non-Craft levels as well.  +cc @ryansloan

I think this is probably a core Blockly bug and won't meet the bug bar for Hour of Code, but tagging @Hamms in case he thinks it'd be an easy fix.

![screen shot 2017-10-16 at 1 50 46 pm](https://user-images.githubusercontent.com/413693/31634790-8185a0ca-b279-11e7-926a-e33425825111.png)

**Comment by joshlory** [comment]
Talked to @ryansloan.  We think unfortunately this is a won't-fix for this year because it takes 40+ blocks to be visibly mis-aligned, which isn't a primary scenario.

**Comment by Hamms** [comment]
I'll also mention (mostly for posterity) that I played around with this a bit and it actually seems to make a difference where the block is coming from. Namely, blocks dragged directly from the toolbox will tend to do this, but blocks created with copy+paste won't, and if the blocks start doing this then grabbing them, detaching, and reattaching will fix it.

I suspect it's exclusively an issue with the toolbox.
