### ISSUE TITLE
Miniblocks not picked up when rolling over them in Minecart

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#244]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10

In Level 10, the player uses Steve to board a Minecart and ride through the tracks to victory. However, if Steve passes near or over miniblocks, Steve does not automatically pick them up as he does in Minecraft.

Steps:
1. Load Level 10
2. Write code to solve the puzzle via Minecart
3. Have Steve use the Minecart
4. Observe miniblocks on the ground

Attachments:
![ezgif-1-9c4cfea809](https://user-images.githubusercontent.com/31709758/31360809-f674d010-ad04-11e7-8d6e-2d83c48ca6b0.gif)

**Comment by joshlory** [comment]
Nice find!  It also looks like the z-index of the minecart is a bit off (renders above the wall to the south in the beginning of the gif).

@WilliamHarmonMS is this a side effect of not changing the indicator and player location while animating the minecart?
