### ISSUE TITLE
Agents boinking into objects while on Pressure Plates causes Doors to close but look open

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#254]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/3

If an Agent is on a Pressure Plate and runs into a wall, it causes the Pressure Plate to quickly deactivate and reactivate which in turn causes connected Redstone items to visually deactivate and reactivate. However, they do not actually reactivate and in the case Level 3, makes it impossible to complete.

Steps:
1. Load Level 3
2. Write code so that the Agent bonks into the wall on the Diamond Pressure Plate
3. Run the code
4. Observe Agent boinking into the edge of the map
5. Attempt to walk Steve through a door

Attachments:
![ezgif-4-f07969b97c](https://user-images.githubusercontent.com/31709758/31416226-9e8ef3d4-addc-11e7-86ef-fca73d10e946.gif)

**Comment by joshlory** [comment]
Verified this issue is now fixed.
