### ISSUE TITLE
Torch is not generating light source at level 8

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#258]
Found at:
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/8

Torch is not generating light source at level 8. Please notice that entire level is dark, and Lava block located at the opposite side of Torch is generating light, which differs from Torch behavior. 
 
Steps:
Load level 8.
Notice the issue.

Notes:
![light](https://user-images.githubusercontent.com/20599143/31447823-2950b9c8-aea3-11e7-9b71-51f3450f74f4.jpg)

**Comment by joshlory** [comment]
Actually I think this is a curriculum issue.  The torch is on the `groundDecorationPlane` instead of the `actionPlane`.  I will update the level.

**Comment by joshlory** [comment]
Should be fixed now!
