### ISSUE TITLE
Information in "Puzzle 1 completed." window is not adjusted to actual Player actions

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#260]
Found at:
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1
 
Information included in "Puzzle 1 completed." is misleading - In this particular level User is not using any coding blocks and only navigates his Character by keyboard/touch controls. 
 
Steps:
Load level 1.
Complete the level.
Notice the message.

Attached file: 
![message](https://user-images.githubusercontent.com/20599143/31448194-25fd4722-aea4-11e7-8fc2-0b8a242cafcd.jpg)

**Comment by joshlory** [comment]
We should also remove the "Replay" button on this dialog, or update it to also reset the level state.  Without a "Run" button on the level there's no way to replay it.

**Comment by ryansloan** [comment]
No longer an issue with new level designs.
