### ISSUE TITLE
"Less" button is not working in levels: 7, 8 and 9

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#262]
Found at:  
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/7
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/8
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/9
 
 In levels: 7, 8 and 9 “less” button (placed next to instructions) is not working.

Steps:
1. Load Level 7.
2. Click „Less” button (next to instructions).
3. Observe that less button is not working.
 
Attachments:
[less_button_not_working.zip](https://github.com/code-dot-org/craft/files/1376080/less_button_not_working.zip)

**Comment by joshlory** [comment]
I no longer repro on levels 7-9, but I do repro on https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/11.

I think it's just missing non-markdown instructions?

**Comment by kiki-lee** [comment]
They all now have simple instructions.
