### ISSUE TITLE
Inconsistent instruction of level 1

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#263]
Found at: 
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1

In instruction of level 1 after clicking “more” button (placed next to instructions) user can read: “Can you get the player to the pressure plate to open the door?” despite that there’s no pressure plate and the door in this level.

Repro Steps:
Load Level 1.
Click „More” button (next to instructions). 
Observe that question: “Can you get the player to the pressure plate to open the door? Is inconsistent with this level because there’s no pressure plate and the door in this level.

Attachments:
![lvl_1_instuction](https://user-images.githubusercontent.com/20599143/31449202-9365e18c-aea6-11e7-8c0c-100338510004.jpg)

**Comment by joshlory** [comment]
Appears to be fixed now.
