### ISSUE TITLE
Steering the Steve or Alex by touch navigation on Microsoft Surface Pro device frequently becomes unresponsive

### ISSUE THREAD

**Issue by LB-wokuja** [code-dot-org/craft#264]
Found at:  All levels
 
Frequently when user is steering the Steve or Alex by touch navigation on Microsoft Surface Pro device, the Steve or Alex do not stop after moving one block but keep moving forward and User have to click the screen to stop them.   

 
Steps:
1. Load any Level on Microsoft Surface pro on Microsoft Edge browser.
2. Click „Run” button.
3. Steer the Steve or Alex by Touch.
4. Observe that sometimes Steve or Alex do not stop after moving by one block but keeps moving forward.
 
Attachments:
[irresposive_steering_touchscreen.zip](https://github.com/code-dot-org/craft/files/1376186/irresposive_steering_touchscreen.zip)

**Comment by joshlory** [comment]
This should be fixed when https://github.com/code-dot-org/code-dot-org/pull/18348 ships.  Thanks Elijah!

**Comment by Hamms** [comment]
I actually think this is unrelated to that fix
