### ISSUE TITLE
Sticky piston pulls torch off of goal in Level 12

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#265]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/12](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/12)

On Level 12, when the agent destroys the redstone torch to retract the piston blocking the player's path to the goal, the torch on the goal moves off the orange block.

1. Load Level 12
2. Program the agent to destroy the redstone torch
3. Observe non-redstone torch 

Actual result: Sticky piston pulls torch off of goal
Expected result: Sticky piston is changed to regular piston

![goaltorch](https://user-images.githubusercontent.com/26069359/31461069-2e082f94-ae7d-11e7-8e5b-72dd9f044e88.png)

**Comment by joshlory** [comment]
Should be fixed.
