### ISSUE TITLE
When both Steve and the Agent strike/destroy at the same time player losses control of Steve.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#267]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/11

Whenever Steve and the Agent are at the same location:
The Agent bumps into the block while Steve attempts attack/use on a block the player loses all control of Steve.

**Repro Steps:**
1) Start level 11.
2) Create a loop that moves the agent and destroys blocks until it hits a block  (Keep the loop going so Steve can get to the same location).
3) Start the simulation.
4) Move Steve to the same location the agent is in.
5) Hit the space bar to use/attack the block.

**Expected Results:**
The player does not lose control of Steve.

**Actual Results:**
The Player does lose control of Steve.

**Notes:**
The wall around the map also reproes this issue.

**Video:**
Shows this happen on the wall but it also happens on any indestructible block on the map.
[Microsoft Edge 10_11_2017 2_37_54 PM.zip](https://github.com/code-dot-org/craft/files/1377281/Microsoft.Edge.10_11_2017.2_37_54.PM.zip)

**Comment by joshlory** [comment]
Tracking under issue https://github.com/code-dot-org/craft/issues/209.
