### ISSUE TITLE
Infinite animation loop – When the agent destroys specific items.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#269]
When the Agent destroys some items, the agent gets put into an infinite animation loop. Giving the agent, any other command will cause the animation to break.

Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/13

**Repro Steps:**
1)	Start level 13
2)	Place the destroy block as the only command.
3)	Run the simulation.
4)	Observe the Agent.

**Actual Results:**
The Agent is placed in an infinite destroy animation loop.

**Expected Results:**
After the destruction of the block the Agent is placed in the idle animation loop.

**Notes:** 
So far I have found this occurs for Redstone wire, Redstone Torch, sandstone, and stone (Level 4 block attached to sticky piston)

**Video:**
[Microsoft Edge 10_12_2017 8_45_35 AM.zip](https://github.com/code-dot-org/craft/files/1379872/Microsoft.Edge.10_12_2017.8_45_35.AM.zip)

**Comment by alalb** [comment]
https://github.com/code-dot-org/craft/pull/268
