### ISSUE TITLE
No music plays for any of the Levels

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#271]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1

Unlike previous years, no music can be heard in any of the Minecraft levels.

Steps:
1. Load any level
2. Listen for the music

Attachments:
None.

**Comment by joshlory** [comment]
Should be fixed when https://github.com/code-dot-org/code-dot-org/pull/18373 ships!
