### ISSUE TITLE
Allow referring to "Steve" or "Alex" by name in level instructions

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#294]
Request from @kiki-lee.

![image](https://user-images.githubusercontent.com/413693/31568056-489aa516-b027-11e7-9a60-6b6f633cdade.png)

Add a `{currentPlayerName}` token that can be used in the instructions to refer to the current player (Alex or Steve).

**Comment by Hamms** [comment]
One thing to note is that we're not going to be able to support this for whichever level the player select dialog is actually on, since all instructions calculation needs to happen at page load time and isn't able to be updated.

**Comment by Hamms** [comment]
Functionality will be added by https://github.com/code-dot-org/code-dot-org/pull/18457 FYI @kiki-lee
