### ISSUE TITLE
Pressing "use" on a chicken causes the player to freeze

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/craft#296]
Low priority for now, but we may add some mobs to the maps and would like to use chickens.

**Comment by joshlory** [comment]
We should confirm this doesn't also affect Designer.

**Comment by kiki-lee** [comment]
This might be a bigger deal than we think.  The first thing I did today in testing level 1 was to go "use" the sheep, and I froze.  That's a bad way for students to start the tutorial, especially since the only fix seems to be a reload.

**Comment by joshlory** [comment]
@kiki-lee we have a fix, it's just waiting for review.
