### ISSUE TITLE
Moving the player to the orange square does not complete Level 4

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#299]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/4](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/4)

Moving the player to the orange square marked with the torch does not complete the level.  Instead, the goal is one square below the orange square.

1. Load Puzzle 4
2. Move the player to the orange square with the torch (without stepping on the square below it)
3. Move the player down one square

Actual result: Moving player to orange square does not complete level
Expected result: Moving player to orange square completes level

![level4](https://user-images.githubusercontent.com/26069359/31624028-2cd58c52-b256-11e7-979f-6b22f0077ee7.png)

**Comment by joshlory** [comment]
Fixed!
