### ISSUE TITLE
Music for Level 5 is missing

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#301]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/5

With the addition of ambient music to the levels, levels now play Minecraft specific background music. However, Level 5 appears to have not been updated with this inclusion and remains silent. 

Steps:
1. Load Level 5
2. Listen for music

Attachments:
None.

**Comment by joshlory** [comment]
Fixed.
