### ISSUE TITLE
Unable to reset Level 1

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#302]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/1

With the removal of the "Run" button in Level 1, players are able to move Steve around without needing to press the button. However, since the button has been removed, there isn't a new button available that allows the player to reset the level. If the player's complete the level (get to the orange block and summon the agent), they are stuck there until the webpage is refreshed.

Note, pressing "Start Over" in the workspace gives a proper warning prompt, but still doesn't actually reset the level.

Steps:
1. Load Level 1
2. Complete Level 1
3. Select "Replay"
4. Attempt to restart the level

Attachments:
![ezgif-4-2b7a80332d](https://user-images.githubusercontent.com/31709758/31626645-619e6388-b25f-11e7-814e-16d2a55ae755.gif)

**Comment by joshlory** [comment]
Similar issue exists on https://studio.code.org/s/minecraft/stage/1/puzzle/4, but that level also has a "Reset" button.

See related issue https://github.com/code-dot-org/craft/issues/260 to remove the "Replay" button from the puzzle completion dialog.

**Comment by joshlory** [comment]
Assigning @ryansloan to triage & recommend a best course of action.  Thanks Ryan!

**Comment by ryansloan** [comment]
No longer an issue, now that the first level has been replaced
