### ISSUE TITLE
Solution shown in hint for Level 6 is based on start square from previous version of puzzle

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#303]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/6](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/6)

The solution demonstrated in the final hint for Puzzle 6 is based on a previous version of the map, where the agent's starting location was one spot to the right of the current starting location for the agent.

1. Load Puzzle 6
2. Open all the hints
3. Observe proposed solution

Actual result: Proposed solution, while optimal for previous version of puzzle, involves extra instructions for current version of puzzle
Expected result: Proposed solution is optimal for current version of puzzle

![level6solution](https://user-images.githubusercontent.com/26069359/31627008-97e50ad6-b260-11e7-9699-e563dad91e17.png)

**Comment by kiki-lee** [comment]
Removed animation
