### ISSUE TITLE
Diamond miniblock in Level 4 is not sitting on a Diamond Block

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#305]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/4

As opposed to every other level that features a collectible diamond, the Diamond in Level 4 is not sitting ontop of a Diamond Block.

Steps:

1. Load Level 4
2. Observe Diamond miniblock

Attachments:
![hoc_level4_diamond_notondiamondblock](https://user-images.githubusercontent.com/31709758/31627991-0d976ad2-b264-11e7-8db7-333fbc09eb7f.jpg)

**Comment by joshlory** [comment]
Fixed.
