### ISSUE TITLE
Level 6 unnecessarily provides a code block for destroy

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#306]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/6](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/6)

The destroy block is not necessary for the completion of Puzzle 6 (even if the player wants to collect the diamond) and yet it is included in block section.  This is inconsistent with other levels 1-9 where destroy isn't necessary; level 10 is where destroy is introduced, since it is required to solve the puzzle.

1. Load Puzzle 6
2. Observe available code blocks

Actual result: Destroy is available
Expected result: Destroy is not available

![level6destroy](https://user-images.githubusercontent.com/26069359/31628123-8fac3a52-b264-11e7-9d8a-fcd798380cb1.png)

**Comment by joshlory** [comment]
Same base issue as https://github.com/code-dot-org/craft/issues/259.  Linking to that bug so they are tracked together!
