### ISSUE TITLE
Second Hint in Level 2 incorrectly labels the "Run Agent" button

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#307]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/2

Reading through the provided hints in Level 2, the second hint incorrectly refers to the "Run Agent" button as "Run".

Steps:
1. Load Level 2
2. Examine the second hint

Attachments:
![hoc_level2_secondhint_wrongbuttonname](https://user-images.githubusercontent.com/31709758/31628359-53bdb646-b265-11e7-99a8-4567d6addaca.jpg)

**Comment by joshlory** [comment]
Fixed!
