### ISSUE TITLE
Hints in Levels 4 and 9 incorrectly labels the "Run Agent" button

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#311]
Found at: https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/4 and https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/9

Reading through the provided hints in Level 4 and 9, both levels provide a hint that refers to the "Run Agent" button as "Run". In Level 4, the 3rd hint and in Level 9, the 1st hint. 

(Probably should have written these all as one, oops)

Steps:
1. Load Level 4 or 9
2. Examine the hints 

Attachments:
![hoc_level4_thirdhint_incorrectbutton](https://user-images.githubusercontent.com/31709758/31635219-dd6c23b8-b27a-11e7-89b2-7e0bb595dbdd.jpg)
![hoc_level9_firsthint_incorrectbutton](https://user-images.githubusercontent.com/31709758/31635222-dec6caf6-b27a-11e7-88c8-ea876a9175e9.jpg)

**Comment by joshlory** [comment]
Fixed, thank you for the report!

If we change the text of the button again we should also do a pass through all the hints to update the text there as well.
