### ISSUE TITLE
Levels 5, 7 and 11 do not have hints

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#312]
Found at: 
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/5
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/7
https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/11

No hints are provided in Level 5, 7, and 11 leaving players to fend for themselves if they become stuck or need help.

Steps:
1. Load Level 5, 7, or 11
2. Look for Hints

Attachments:
![hoc_level5_nohints](https://user-images.githubusercontent.com/31709758/31635483-b8dcbd7c-b27b-11e7-98d2-6371c32ea87b.jpg)
![hoc_level7_nohints](https://user-images.githubusercontent.com/31709758/31635495-c7d5aa46-b27b-11e7-83bd-e206b22e63ab.jpg)
![hoc_level11_nohints](https://user-images.githubusercontent.com/31709758/31635523-db6004c6-b27b-11e7-91a4-38ddb51c7d0b.jpg)

**Comment by kiki-lee** [comment]
Basic hints added.  Complete run-through will be done when level design is locked.
