### ISSUE TITLE
Level 10 does not provide a block for a user to create a function

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#315]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10)

After having been introduced to functions in Puzzles 8 and 9, it seems odd that there is no block for the users to define their own function for solving Puzzle 10.  While a simple loop can be used to clear the path to the goal, having a function seems applicable to get to the diamond.  Using a function would not be required, but it would be a useful example of how functions can be used well.

1. Load Puzzle 10
2. Write a solution to clear a path to the goal square
3. Add code to the solution to also clear a path to the diamond
4. Observe repeated code

Actual result: User re-uses same lines of code in different parts of solution
Expected result: User can use a function to call a section of code multiple times in solution

![level10nofunction](https://user-images.githubusercontent.com/26069359/31677309-335acae6-b31f-11e7-87c6-ba532839c348.png)

**Comment by kiki-lee** [comment]
This is no longer a functions level.  It's now a loops level.
