### ISSUE TITLE
Level 10 hint is based on previous version of puzzle and is not correct for the current solution

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#316]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/10)

The hint for Puzzle 10 says to use a "Repeat 2" loop, which worked for a previous version of the map where there were two cactus blocks between the agent and the goal.  Now that there are three cactus blocks between the agent and the goal, a "Repeat 3" loop is the optimal solution.

1. Load Puzzle 10
2. Open hint
3. Observe puzzle

Actual result: Outdated hint is not optimal for solution to current version of puzzle
Expected result: Hint is updated for optimal solution of puzzle

![level10hint](https://user-images.githubusercontent.com/26069359/31677667-6ab432ec-b320-11e7-906d-7f75bbb44d00.png)

**Comment by alalb** [comment]
Fixed.
