### ISSUE TITLE
Walking the player into the right half of the nether portal does not complete Level 11

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#317]
Found at: [https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/11](https://levelbuilder-studio.code.org/s/colehoc2017/stage/1/puzzle/11)

The description for Puzzle 11 instructs the player to "walk into the nether portal." However, only the left half of the nether portal is considered as the goal.  If the player walks into the right half of the nether portal, nothing happens.

1. Load puzzle 11
2. Have the agent clear a path to the nether portal
3. Move the player into the right half of the nether portal
4. Observe

Actual result: Player does not complete level
Expected result: Player completes level

![level11goal](https://user-images.githubusercontent.com/26069359/31678919-66a46934-b324-11e7-9cc5-eb732551209e.png)

**Comment by joshlory** [comment]
I've updated the verification function to check both locations:
```js
function (verificationAPI) {
      // player is at given x, y position
      return verificationAPI.isPlayerAt([4, 8]) || verificationAPI.isPlayerAt([5, 8]);
}
```
