### ISSUE TITLE
`Place` items not alphabetized in dropdown

### ISSUE THREAD

**Issue by kiki-lee** [code-dot-org/craft#324]
I went through and alphabetized the items that can be placed in freeplay (otherwise the long list is hard to navigate) but they're still showing randomly in the block dropdown.  

https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/11

**Comment by joshlory** [comment]
@ryansloan let me know if you're not able to solve this via a well-understood Level Builder edit and we can add it to the dev backlog.

**Comment by ryansloan** [comment]
Hmm, @kiki-lee Are you still seeing this problem? They look alphabetized to me
![screen shot 2017-11-01 at 1 32 20 pm](https://user-images.githubusercontent.com/1669271/32296320-24492a66-bf09-11e7-81d7-e612cb823710.png)

**Comment by kiki-lee** [comment]
Now that we don't have any levels that utilize more than a handful of the options, I don't think it will be an issue.  Before, when trying to add things, they would show up in the order of the default array, regardless of the order that you entered them.

**Comment by alalb** [comment]
The place items on level 12 will be alphabetized. Elijah is adding the colored wool to the placeable items.

**Comment by ryansloan** [comment]
Won't fix - we've grouped the items by type
