### ISSUE TITLE
'Run Agent' with no code warning message

### ISSUE THREAD

**Issue by WilliamHarmonMS** [code-dot-org/craft#330]
If a student clicks the 'Run Agent' button with no blockly code attached to 'run', there should be a message that notifies them that something is wrong. Something along the line of "The Agent doesn't know what to do!"

**Comment by Hamms** [comment]
This is not a specific failure case we can detect without a bunch of extra work to enable it; rather, the level-specific failure messages should be written in such a way as to direct the player's attention toward the Agent.

**Comment by ryansloan** [comment]
^ What Elijah said, we should just write the failure message overrides for this. It's a good idea but the platform doesn't support it right now, and anything more is out of scope at this point.
