### ISSUE TITLE
Unpowering redstone wire should stop the sparkle animation

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#335]
Repro: destroy the redstone torch on https://code-dot-org.github.io/craft/.

![image](https://user-images.githubusercontent.com/413693/31747962-d88f687c-b424-11e7-9643-eaaea43a278b.png)

**Comment by WilliamHarmonMS** [comment]
fix in [PR#384](https://github.com/code-dot-org/craft/pull/384)

**Comment by WilliamHarmonMS** [comment]
384 was merged, so closing.
