### ISSUE TITLE
Agent can destroy obsidian blocks used for frame of nether portal

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#342]
Found at: [https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10)

The user can program the agent to destroy the obsidian blocks that form the frame for the nether portal.  Destroying such a block causes a breaking animation to play and an obsidian item to drop, but visibly the obsidian remains.  However, there is no longer an actual block where the obsidian block was, as the agent can move into that spot.  Also, the nether portal effect remains active, not at parity with Minecraft gameplay.

1. Load puzzle 10 at the address provided above
2. Program the agent to destroy an obsidian block and move to into the vacated spot

Actual result: Having the agent destroy obsidian blocks creates several undesirable scenarios.
[destroyObsidian.zip](https://github.com/code-dot-org/craft/files/1399713/destroyObsidian.zip)

**Comment by alalb** [comment]
Will be fixed by: [PR369](https://github.com/code-dot-org/craft/pull/369)

**Comment by WilliamHarmonMS** [comment]
369 was merged, so closing this.
