### ISSUE TITLE
User can modify definitions of functions "fix right corner" and "fix left corner"

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#343]
Found at: [https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10)

1. Load puzzle at link provided above
2. Add or remove code from the provided functions

Actual result: User can modify provided functions
Expected result: User cannot modify provided functions

![cornerfunctions](https://user-images.githubusercontent.com/26069359/31790767-6dfcd0ba-b4cb-11e7-8699-e5fc7136fe93.png)

**Comment by alalb** [comment]
Fixed.
