### ISSUE TITLE
User is prevented from clicking "Run Agent" button by overlapping video help link

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#344]
Found at: 
[https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/2](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/2)
[https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/4](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/4)
[https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/8](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/8)

The user cannot click the button "Run Agent" because there is other text/UI in the way

1. Load any of the puzzles at the links provided above
2. Attempt to click the "Run Agent" button.

Actual result: User cannot click button
Expected result: Video and text are moved so that user can click button
![videovsbutton](https://user-images.githubusercontent.com/26069359/31791359-2ac15c74-b4cd-11e7-85a9-ba9658a160e4.png)

**Comment by joshlory** [comment]
Will be fixed by https://github.com/code-dot-org/code-dot-org/pull/18500.
