### ISSUE TITLE
Shadow on block is not updated after the block that is "casting" the shadow is removed.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#348]
Found In: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/9

On the 10th level a shadow of a cactus does not update after the cactus is removed on the sandstone block.

1) Start level 9.
2) Use the method clear path 3 times.
3) Observe the shadow cast by the cactus remains after the cactus has been removed.

Expected Results:
All shadows cast by an object are removed when the object is destroyed.

Actual Results:
If a block casting a shadow on another block in the same plane is destroyed the shadow remains.

Video:
[shadows on the block.zip](https://github.com/code-dot-org/craft/files/1400079/shadows.on.the.block.zip)

**Comment by v-jaarba** [comment]
Found in other levels where a shadow was cast by a block onto another block on the same height.

**Comment by joshlory** [comment]
![image](https://user-images.githubusercontent.com/413693/31797737-bf232f52-b4e4-11e7-9b7b-258aebfb40ff.png)

Shadow is missing when new blocks are first placed, and aren't removed correctly.
