### ISSUE TITLE
Level 2 message is incorrect, the agent only moves once and does not make it to the pressure plate.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#350]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/2

The messages we give to the students should be accurate. This message indicates that when the agent run is pressed the code that is in the workspace should move the agent to the pressure plate and open the door. That does not happen.

Repro Steps:
1) Start level 2.
2) Read the message.
3) Press the Run Agent button.

Actual results:
The agent does not do what the message says it should with the initial workspace blocks.

Expected Results:
The initial workspace has two move forward blocks to do what the message says. Or the message is changed to not confuse users.

Video:
[Level2Message.zip](https://github.com/code-dot-org/craft/files/1400204/Level2Message.zip)

**Comment by ryansloan** [comment]
Resolved with new instructions.
