### ISSUE TITLE
Level 10 - Message says to walk into nether Portal but the win condition spot is ouside of it.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#352]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10

The Level 10 message is telling the player to do one thing but the level is built so that they want to collect the flint and steel. The level also has 2 win condition blocks that are in front of the portal not in the portal.

Repro steps:
1) Start level 10.
2) Read the message.
3) Have the agent get through the level.
4) Attempt to enter the portal.

Expected Results:
Change the message to indicate the player should collect the flint and steel and remove the other win condition spot to the right of the flint and steel. Or Remove the flint and steel from the level and move both win condition spots to inside the portal.

Actual Results:
The player wins before reaching the portal. They may not even attempt to collect the flint and steel as they attempt to enter from the second spot to the right of them.

Video:

[Message is incorrect.zip](https://github.com/code-dot-org/craft/files/1400285/Message.is.incorrect.zip)

**Comment by alalb** [comment]
Instructions were updated for all the levels. Fixed.
