### ISSUE TITLE
Birch tree is growing on water in free play level

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#359]
Found at: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/12

Destroying the birch tree near the top of the screen reveals that the tree was floating above water

1. Load the free play level
2. Program the agent to destroy the tree near the top of the screen
3. Observe type of block underneath where tree previously stood

Actual result: Tree was floating on water
Expected result: Grass or dirt block beneath tree

[birchTree.zip](https://github.com/code-dot-org/craft/files/1408014/birchTree.zip)

**Comment by joshlory** [comment]
I think the final free-play level is changing, but waiting to hear back from @alalb!

**Comment by ryansloan** [comment]
Won't Fix, this isn't the actual free play level
