### ISSUE TITLE
Less button doesnt collapse text in Levels 2 and 3

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#362]
Found at: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/2

A player working through Levels 2 or 3 needs help and views the various hints provided. After reading the hints, the player wants to reclaim the visual real estate for the Workspace and presses the Less button. For some reason for these two levels (and not the others), the Less button does not work and does not collapse the hints and text down to the simple one liner.

Steps:
1. Load Level 2 or 3
2. Expand the Hints out
3. Press the Less button and observe results
4. Repeat Step 3 a few times

Attachments:
![ezgif-3-cebfd7ca0c](https://user-images.githubusercontent.com/31709758/31907579-198baa9e-b7e9-11e7-8251-72ab4fa6ff13.gif)

**Comment by joshlory** [comment]
I think these are just missing non-markdown instructions.

**Comment by v-jaarba** [comment]
This also occurs in level one.

**Comment by joshlory** [comment]
@v-samtha @v-jaarba I'm no longer able to repro on levels 1-3.  I think this might be fixed now?

**Comment by v-samtha** [comment]
@joshlory looks fixed to me

**Comment by joshlory** [comment]
Thanks!  Closing.
