### ISSUE TITLE
When selecting from a drop-down box the workspace can be put in a state that moves up uncontrollably. 

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#363]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10

The workspace window can be placed in a state that continues to scroll up. This can be fixed with placing any block into the workspace. This only seems to occur in the pre built functions.

**Repro Steps:**
1) Start level 10.
2) Move a function down so that some of the code is below the visible workspace.
3) Open the place blocks drop-down menu in the function.
4) Click outside of the drop-down menu on the place block itself.
5) Observe the workspace window.

**Expected Results:**
The workspace window remains in the users control.

**Actual Results:**
The workspace window is no longer in the users control.

**Video:**
[WorkspaceGhostControl.zip](https://github.com/code-dot-org/craft/files/1408495/WorkspaceGhostControl.zip)

**Comment by ryansloan** [comment]
We will lock down the blocks so they can't change it.

**Comment by alalb** [comment]
This is almost impossible to repro and currently only occurs on the free play level.

**Comment by ryansloan** [comment]
We are good with "Won't Fixing" this.
