### ISSUE TITLE
Level 8 - Functions can be permanently deleted with the keyboard.  

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#370]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/8

The functions that are not supposed to be manipulated can be duplicated and deleted with keyboard button presses. This can lead to duplicates with a number of functions that overlap making it hard to get to the original function. As well as the user can delete the function all together causing the level to be unbeatable. The fix would be to refresh the page but this can cause frustration with younger users if they accidentally hit delete on a function.

**Repro Steps:**
1) Start level 8.
2) Select the function.
3) Hit delete on the keyboard.

**Expected Results:**
The function can be replaced if the user accidentally deletes it. Or the ability to delete the function is removed.

**Actual Results:**
The function can be deleted and makes the level unbeatable.

**Video:**
[DeleteFunctionNoFun.zip](https://github.com/code-dot-org/craft/files/1409092/DeleteFunctionNoFun.zip)

**Comment by v-jaarba** [comment]
This can not be done with the function in level 9.

**Comment by v-jaarba** [comment]
Level 10's function can be copy and pasted resulting in code that can not be moved or removed from the workspace. If all functions worked the same and removed keyboard shortcut commands this will fix this issue too.

**Comment by alalb** [comment]
I fixed all these issues for level 8 and 10. closing.
