### ISSUE TITLE
Ghasts do not make any sfx

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#372]
Found at: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/11

In Level 11, Ghasts float around in the Nether based level. However, all they do is float and animation. No sound effects can be heard from them.

Steps:
1. Load Level 11
2. Listen to the creep music
3. Observe that Ghasts make no sounds at all

Attachments:
None.

**Comment by joshlory** [comment]
Ghasts now add ambient noise when they are present in a level.  Proximity audio is out of scope unfortunately.
