### ISSUE TITLE
Function names can be used to overide functions in javascript code.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#383]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/12

Someone could accidentally use function names that are in javascript that would override that functionality.
So far I have only tested block code from this project but if some functions are useable then problems could occur.

Repro Steps:
1) Start level 12
2) rename the function to "destroyBlock"
3) Add code to the Function.
4) Set the block to run on command.
5) Run the code.

Expected Results:
Names must be regulated or function code could be overwritten.

Actual Results:
Function names are capable of overwriting other code blocks.

Video
[OveridingFunctions.zip](https://github.com/code-dot-org/craft/files/1416479/OveridingFunctions.zip)

**Comment by v-jaarba** [comment]
it looks like functions outside of this program do not get overwritten.
the function name gets assigned sub numbers if it finds functions that would have overwritten code.

**Comment by ryansloan** [comment]
This is a Won't fix
