### ISSUE TITLE
Users can delete code before finishing the level to decrese the code count they used.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#388]
Found In: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/4

This may cause problems if the teachers want accurate code counts from students. It will also cause trouble if we want to implement optimal code paths as previous HoC years.

Repro Steps:
1) Start level 4.
2) Create code so the level can be completed. 
3) Run the code.
4) Maneuver Steve/Alex to the tile adjacent to the win location.
5) Delete all the code from the workspace.
6) Move Steve/Alex onto the win location.

Expected Results:
The code count is tabulated at the time run is pressed.

Actual Results:
Code count is not counted until win condition is completed.

Video:
[CodeCountModify.zip](https://github.com/code-dot-org/craft/files/1422859/CodeCountModify.zip)

![code org levelbuilder - craft17 development script 4 - google chrome 10_27_2017 10_13_55 am](https://user-images.githubusercontent.com/32551617/32116536-dc1f65c8-baff-11e7-9429-f24f92ce3d94.png)

**Comment by ryansloan** [comment]
Won't Fix
