### ISSUE TITLE
Multiple goal squares allow player to complete Level 10 without collecting item

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#389]
Found at: [https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10)

The goal in Level 10 is unclear.  There are two goal squares in front of the nether portal, one of which is marked with an item to collect.  The player can complete the level without collecting the item by standing on the goal square to the right of the collectible item.

1. Load level 10 at address above
2. Program the agent to clear a path
3. Move the player to the square to the right of the collectible item without collecting the item.
4. Observe

Actual result: Player completes level without collecting item
Expected result: Player must collect item to complete level

![level10goal](https://user-images.githubusercontent.com/26069359/32117152-26dd825a-bb02-11e7-9a23-cd4496be3eaf.png)

**Comment by alalb** [comment]
Victory point was updated. Fixed.
