### ISSUE TITLE
Level 9 - Can not complete level.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#390]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/9

The new layout for level 9 can not be completed. There is no place block in the level to be able to place items in the water so the user can not finish the level.

Repro Steps:
1) Start level 9.
2) Use the function clear path to get through the ice blocks.
3) Observe the water blocks that can not be changed with place.

Expected Results:
Some form of place is added to the level or the water is removed from the level.

Actual Results:
Without the ability to place blocks this level can not be completed.

Video:
[icePlaceBlocks.zip](https://github.com/code-dot-org/craft/files/1422951/icePlaceBlocks.zip)

**Comment by v-jaarba** [comment]
Has been fixed already

**Comment by alalb** [comment]
Fixed. 
The functions were updated.
