### ISSUE TITLE
User can delete code from non-deletable functions

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#392]
Found at: [https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/9](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/9)

For functions that are protected from the player dragging code blocks out of the function definition, the player can still remove code blocks by right-clicking them and pressing Delete on the keyboard.  Pressing the Reset button does not restore the code; instead the player must press the Start Over button to restore the function to its original definition.  The Start Over button is not explained to the player through any of the hints, unlike the Run Agent / Reset button.  In Level 9, deleting the Destroy code block would be a blocker if not for the Start Over button.

1. Load the level at the address provided above
2. Right click a code block in the provided function
3. Press the Delete key
4. Observe

Actual result: User can remove code from functions
Expected result: User can not remove code from functions

![deletecode](https://user-images.githubusercontent.com/26069359/32117810-776a8608-bb04-11e7-8c69-2f59c0f4d838.png)

**Comment by alalb** [comment]
Fixed.
