### ISSUE TITLE
Guide Line hint for level 5 does not match current layout.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#393]
Found In: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/5

The hint for Level 5's guide line does not match the starting position or the end position for the new layout of the level.

Repro Steps:
1) Start level 5.
2) Activate the hint for this level.
3) Observe.

Expected Results:
The hint matches all other levels that have the guide line hint. Start and stop positions matching the level layout.

Actual Results:
This level is the only level where the guide line hint does not start and stop at the appropriate locations.

Picture:
![guidelinesgonowhere](https://user-images.githubusercontent.com/32551617/32118299-f8891820-bb05-11e7-8778-422349aad206.png)

**Comment by alalb** [comment]
Fixed.
