### ISSUE TITLE
Level does not complete when player reaches goal if function is empty

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#394]
Found at: [https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10)

If a function definition is empty when the player reaches the goal, the level does not complete.  

1. Load level at address provided above
2. Delete the code inside one of the functions (right click the code blocks, then hit Delete key)
3. Program the agent to clear a path to the goal
4. Move the player to the goal
5. Observe

Actual result: Level is not complete
Expected result: Level is complete

![level10fail](https://user-images.githubusercontent.com/26069359/32118272-e78d0cf2-bb05-11e7-99ee-b1677b516057.png)

**Comment by kiki-lee** [comment]
Do we just want to make it so the function cannot be emptied?

**Comment by joshlory** [comment]
Moved to Trello: https://trello.com/c/XTKspC5m/120-level-does-not-complete-when-player-reaches-goal-if-function-is-empty
