### ISSUE TITLE
Destroy animation does not play when agent is destroying rails and next command is turn or move

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#395]
Found at: [https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10)

If the agent is programmed to move or turn after destroying a rail, there is no animation to show that the agent is destroying the rail.

1. Load level found at address above
2. Program the agent: turn left, destroy block, move forward
3. Run the code
4. Observe agent animation

Actual result: No animation of agent destroying rails
Expected result: Animation shows agent destroying rails

[destroyRails.zip](https://github.com/code-dot-org/craft/files/1423013/destroyRails.zip)

**Comment by WilliamHarmonMS** [comment]
this is fixed by [PR418](https://github.com/code-dot-org/craft/pull/418)

Though to note: You would get the same behavior with Redstone wire? But no puzzles depend on destroying redstone wire? Is that a circumstance that can feasibly occur?
