### ISSUE TITLE
There are death locations that do not match the current ghast locations in level 11.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#396]
Found In: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/11

The level has been updated and the Ghasts have moved locations but the old location still stops the player from completing the level as if the Ghast was still in the old location. 

Repro Steps:
1) Start level 11.
2) Make the Agent build bridges to the old location of the top right Ghast.
3) Move Steve/Alex to this location.

Expected Results:
Ghasts should only stop the player when they touch the Ghast.

Actual Results:
The player is stopped by an old Ghast location.

Video:
[GhastKillsfromDistance.zip](https://github.com/code-dot-org/craft/files/1423120/GhastKillsfromDistance.zip)

Pictures of Locations:
![code org levelbuilder - craft17 development script 11 - google chrome 10_27_2017 12_04_49 pm](https://user-images.githubusercontent.com/32551617/32120882-1a8b4944-bb0f-11e7-9bdb-40b3323dc777.png)

![code org levelbuilder - craft17 development script 11 - google chrome 10_27_2017 12_09_42 pm](https://user-images.githubusercontent.com/32551617/32121049-c9def620-bb0f-11e7-8485-ed916eff2033.png)

**Comment by alalb** [comment]
Fail blocks were removed. Closing.
