### ISSUE TITLE
The name does not update in the message window after the character selection.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#403]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/1

This causes the messages to have the incorrect name displayed for the avatar chosen by the player.
If the player choses Alex, then Steve will be displayed until the user refreshes the page. It will be confusing for users if they don't see the correct name after selection.

Repro Steps:
1) Start level 1.
2) Select Alex.
3) Observe the Text in the message box will not update.

Expected Results:
The user will see the correct name selected after the user selects their character.

Actual Results:
The user will not see the correct name selected after the user selects their character.

Video:
[NameSelf.zip](https://github.com/code-dot-org/craft/files/1428320/NameSelf.zip)

**Comment by Hamms** [comment]
This is a known limitation of the dynamic naming feature, and as such it should _not_ be used for this first level.

I suggest this be re-opened on Trello as a curriculum bug.

**Comment by v-jaarba** [comment]
I have opened a new card in Trello for this issue.

**Comment by Hamms** [comment]
Thanks!
