### ISSUE TITLE
Regression: player jumps up when placing rails in Adventurer

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#405]
Repros on https://studio.code.org/s/mc/stage/1/puzzle/13.

![place-rails-regression](https://user-images.githubusercontent.com/413693/32195971-42868ee4-bd7c-11e7-9db5-2f2ed8f8fcc5.gif)

**Comment by WilliamHarmonMS** [comment]
Wow. Weird. The player, using placeBlock() on the craft repo does not seem to repro this behavior (at least not on master branch). I'll look into this today.

**Comment by Hamms** [comment]
This level is using placeBlockBelow, I probably regressed this when I tweaked the logic for the hop animation

**Comment by WilliamHarmonMS** [comment]
So I totally see it happening on 2015 level 13.

The line in question is:
if (entity === this.agent || LevelBlock.isWalkable(blockType))

^if we get into that, it shouldn't jump. So... is it possible that it's failing the isWalkable check? I know that level is hard coded as heck (place rails for instance places normal rails for that line in the gif, but on the vertical segment is placing powered rails. This suggests that the block actually being placed is hard coded somewhere and the block we're passing into the placeBlock() could be getting over written somehow and isn't actually the correct "rails" when we go through that command?

**Comment by WilliamHarmonMS** [comment]
@Hamms Or that. Ignore me. 😥

**Comment by Hamms** [comment]
Actually @WilliamHarmonMS you were a lot closer than I was!

**Comment by WilliamHarmonMS** [comment]
Well that's nice for me 😂 but probably not great over all! Because man, that level 13 system must have been sooooo last minute. Place(rails) being normal rails OR powered rails is frighteningly sketchy. You have no -idea- what's going on under the hood!

Perfect PR for Halloween? 😨

**Comment by Hamms** [comment]
👻t̞̩̲̼̺̤͑̑́̈́̏͢ͅe͖͚͔̗̪͈̪̽̉ͦc͍̗̰͂̉́h̼͇̰̯ ͉̳̥̣̪̈̿̔̌͢d͎̼̼̤ͪͯͫ͂͢e̳̘͕͊ͧ͒̑̕b̛͈ͨͤ̽̀ͩt̹̫̤̃̿͋͒͆ 👻
