### ISSUE TITLE
Level 12 - Player can move animal onto miniblock blocking collection of items.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#410]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/12

May be done on purpose to challenge users not to lose diamonds. 
If animals are moveable then players can get into situations that block their progress.
All other levels this is not an issue. 

Repro Steps:
1) Start Level 12.
2) Make code to allow Steve/Alex to move one block above the chicken.
3) Push the chicken onto the diamond.
4) Attempt to get the diamond.

Expected Results:
This may be the effect we want.

Actual Results:
The chicken will block the user from getting the diamond if pushed into the same square.

Video:
[ChickenBlocksDiamond.zip](https://github.com/code-dot-org/craft/files/1429043/ChickenBlocksDiamond.zip)

**Comment by joshlory** [comment]
Moved to Trello: https://trello.com/c/qK0BPX0R/119-level-12-player-can-move-animal-onto-miniblock-blocking-collection-of-items

**Comment by alalb** [comment]
As designed.
