### ISSUE TITLE
Title enters failed state if a repeat loop has no code after player gets to the win location.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#412]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/2

This is like the Function empty failed state, but the title gives the user a message that is unnecessary. The player should have won the level no matter the state the code is in if they have achieved the goal.

Repro Steps:
1) Start level 2.
2) Create code to insure the player can get to the map.
3) Add a repeat loop with no code after the code that allows the player to win.
4) Run the code.
5) Move Steve/Alex to the map (win condition).

Expected Results:
The player wins the level. The message can still be given but the goal was achieved.

Actual Results:
The player gets a win animation and a message about not leaving repeat blocks empty, but still loses the level.

Video:
[UnnecessaryButRight.zip](https://github.com/code-dot-org/craft/files/1429082/UnnecessaryButRight.zip)

**Comment by joshlory** [comment]
@ryansloan should the empty block check happen as soon as the "Run" button is clicked?

**Comment by ryansloan** [comment]
@joshlory Yes, we should check immediately and fail. It's a bummer if they can visually solve the puzzle and then they don't pass

**Comment by joshlory** [comment]
Should be fixed by https://github.com/code-dot-org/code-dot-org/pull/18969.
