### ISSUE TITLE
Edge Browser only - After walking onto a rail the player can only move off the rail if they travel perpendicular to the track when using a keyboard.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#422]
Found in: https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10

Edge Browser Only: Works correctly on Chrome.
The new track controls only allow exit of rails perpendicular from the track. while the user is on the track, pressing the direction buttons following the track will result in getting in the minecart. This causes the issue where the player is at the end of a track line and wishing to move forward (in the direction of the tracks orientation) and being unable to continue as if the player was in a minecart. Using the buttons for movement next to the run button can move Steve/Alex correctly.
Using the wasd keys sometimes work when going left but have not worked going right.
The arrow keys never seem to work.

Repro steps:
1) Start level 10 on Edge.
2) Move Steve/Alex onto the tracks using the keyboard.
3) Attempt to move Steve/Alex off of the rails with the keyboard.

Expected Results:
The player can use any browser and any control scheme to move Steve/Alex.

Actual Results:
The player will get stuck on rails if they attempt to use Edge browser and keyboard.

Video:
[Microsoft Edge 11_2_2017 8_52_21 AM.zip](https://github.com/code-dot-org/craft/files/1438475/Microsoft.Edge.11_2_2017.8_52_21.AM.zip)

**Comment by v-jaarba** [comment]
tested internet explorer: this issue does not occur.

**Comment by WilliamHarmonMS** [comment]
EDGE NOT OFFICIALLY SUPPORTED 😂 

Really though, what's the priority on this one? I can look into it, but I don't have edge on my dev machine.

**Comment by joshlory** [comment]
Which version of Edge did you find this bug on?  I'm unable to repro on https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/10 on Edge 15 (using Sauce Labs).

**Comment by v-jaarba** [comment]
I'm not sure which version of edge I found it on, but as of last week it was still occurring. I tried it today and its does not repro anymore.

**Comment by joshlory** [comment]
Going to resolve for now — if this repros again please comment / re-open!

**Comment by WilliamHarmonMS** [comment]
The Edge exceptions were taken out. I'm currently investigating whether or not I can find any impact on other behavior on this year or previous years.
