### ISSUE TITLE
Default value of "???" in repeat block drop-down menu is invalid

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#423]
Found at: [https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/2](https://levelbuilder-studio.code.org/s/craft17/stage/1/puzzle/2)

Though the repeat block has a drop-down menu to ensure a valid value, the default value of ??? is not a valid value.  Similar to bug #412, if the player reaches the goal with a solution that contains superfluous code with a repeat block using '???', then the player does not succeed at completing the level.

1. Load level 2, 3, 5, 6, or 10
2. Observe default value in repeat block
3. (optional) Reach the goal with a ??? repeat block in the code

Actual result: Default value is ???
Expected result: Default value is 2

![repeatdefaultvalue](https://user-images.githubusercontent.com/26069359/32336962-0216711a-bfae-11e7-8595-abb738bc9ce6.png)

**Comment by kiki-lee** [comment]
This is expected.  It forces students to choose a number.

**Comment by alalb** [comment]
Fixed. All loop blocks were updated by Kiki.
