### ISSUE TITLE
Place direction block does not take into account blocks that are already in those locations.

### ISSUE THREAD

**Issue by v-jaarba** [code-dot-org/craft#445]
Found in: https://studio.code.org/s/hero/stage/1/puzzle/12

This does not follow the same rules set that the other place block follows. If a block is in the current location it should have to be destroyed before anything else can be placed in that location. This will not work in Minecraft and will lead to imported code not working users.

Repro Steps:
1) Start HoC and proceed to level 12.
2) Make code to place two different blocks forward.
3) Run code and Observe.

Expected Results:
If a block is currently in the location the place direction block will not place anything in that location.

Actual Results:
Place Direction blocks will replace anything in a location with a new block.

Video:
[Microsoft Edge 11_15_2017 9_00_40 AM.zip](https://github.com/code-dot-org/craft/files/1475649/Microsoft.Edge.11_15_2017.9_00_40.AM.zip)

**Comment by WilliamHarmonMS** [comment]
[PR449](https://github.com/code-dot-org/craft/pull/449) was closed so this is fixed.
