### ISSUE TITLE
Sand does not fall when placed over water

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#446]
Found at: [https://studio.code.org/s/hero/stage/1/puzzle/12](https://studio.code.org/s/hero/stage/1/puzzle/12)

If the agent uses a place block with a direction (not down) to place sand over water, the sand block does not drop into the water.  This is not at parity with Minecraft.

Repro Steps:
1. Load the free-play level with new omni-directional place blocks at the address above
2. Program the agent to place a sand block over the water
3. Observe sand block

Actual result: Sand block does not fall into water
Expected result: Sand block falls into water
[sandParity.zip](https://github.com/code-dot-org/craft/files/1475665/sandParity.zip)

**Comment by WilliamHarmonMS** [comment]
[PR449](https://github.com/code-dot-org/craft/pull/449) was closed so this is fixed.
