### ISSUE TITLE
Agent's placement animation does not complete when using an omni-directional place block

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#447]
Found at: [https://studio.code.org/s/hero/stage/1/puzzle/12](https://studio.code.org/s/hero/stage/1/puzzle/12)

When the agent places a block with any direction in the drop down menu, its right arm does not completely return to its side.  If the agent performs any other actions, this problem is corrected.  But if the agent's last action is to place a block in a non-down direction, the incomplete animation is quite apparent.

Repro Steps:
1. Load free-play level with omni-directional place blocks at address above
2. Program the agent to place a block in any direction other than down
3. Observe agent's right arm at end of animation

Actual result: Animation does not finish
Expected result: Animation finishes appropriately.
[armAnimation.zip](https://github.com/code-dot-org/craft/files/1475735/armAnimation.zip)

**Comment by WilliamHarmonMS** [comment]
[PR449](https://github.com/code-dot-org/craft/pull/449) was closed so this is fixed.
