### ISSUE TITLE
Emissive lighting won't work for levels larger than 10x10

### ISSUE THREAD

**Issue by Hamms** [code-dot-org/craft#455]
Because the reference object [is indexed by `yIndex.toString() + xIndex.toString()`](https://github.com/code-dot-org/craft/blob/master/src/js/game/LevelMVC/LevelModel.js#L931-L932), which will have collisions for double-digit x and y values

**Comment by joshlory** [comment]
Updated code link:

https://github.com/code-dot-org/craft/blob/5a8b2378b4bfb0e7d9d68de4b768ca947455e9df/src/js/game/LevelMVC/LevelModel.js#L982-L983
