### ISSUE TITLE
Newly-placed prismarine blocks don't change color in sync with existing prismarine

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#480]
See aquatic level 11.

Also, prismarine blocks should fade evenly between colors, instead of switching stepwise.

**Comment by joshlory** [comment]
Guidance from Joel:

> Prismarine do all show the same color I think.
> But since it blends, you don't ever see it switch, and it is so slow, it is just kind of a subtle mood change. :slightly_smiling_face:

+cc @madelynkasula

**Comment by islemaster** [comment]
@madelynkasula Are you still working on this?  If so, will you self-assign it so nobody else picks it up?

**Comment by joshlory** [comment]
Adding a few notes here:

It looks like we can use a single `Phaser.BitmapData` as the texture for multiple sprites.  Then updating the prismarine phase on the texture will cause all mapped sprites to change appearance.

```js
var bmd = gameController.game.make.bitmapData(64, 64, 'foo');
bmd.rect(10, 10, 20, 20, 'red');

gameController.game.add.sprite(200, 200, bmd);
gameController.game.add.sprite(250, 200, bmd);
gameController.game.add.sprite(300, 200, bmd);
```

![image](https://user-images.githubusercontent.com/413693/46974580-45795580-d079-11e8-83d2-3386fd09ba56.png)

Then drawing on `bmd` results in all the sprites being updated: 🎉 

```js
bmd.rect(20, 20, 20, 20, 'blue');
```

![image](https://user-images.githubusercontent.com/413693/46974592-54600800-d079-11e8-9c7e-67d63300ee09.png)

Hoping we can use this to draw a blend between two concurrent prismarine frames, that slowly varies over time.

**Comment by joshlory** [comment]
Here's a super-verbose way to draw a prismarine shared texture that is an 80% blend between frames 0 and 1:

```js
bmd.copy(gameController.game.make.sprite(0, 0, 'blocks', 'Prismarine0'), null, null, null, null, null, null, null, null, null, null, null, null, null, 1.0);
bmd.copy(gameController.game.make.sprite(0, 0, 'blocks', 'Prismarine1'), null, null, null, null, null, null, null, null, null, null, null, null, null, 0.8);
```

**Comment by madelynkasula** [comment]
@islemaster i was _hoping_ to pick it back up, but don't have the bandwidth right now, so i'm going to leave it unassigned. if someone wants to pick it up, i can help get them up-to-speed on the research i did in my first stab at it
