### ISSUE TITLE
FoW edge case: no tile with two opposite corners lit

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#537]
![image](https://user-images.githubusercontent.com/413693/47758159-01847400-dc67-11e8-9dfb-11142e7a97ed.png)

We don't account for two opposite corners being lit, with the remaining two corners in darkness:

https://github.com/code-dot-org/craft/blob/5a8b2378b4bfb0e7d9d68de4b768ca947455e9df/src/js/game/LevelMVC/LevelModel.js#L902-L918

**Comment by joshlory** [comment]
Joel sent me the original FoW solver spec.

![underground_fow_fadingsolution](https://user-images.githubusercontent.com/413693/47760836-7493e780-dc73-11e8-987a-3ad653dc7fdd.gif)

It looks like we aren't correctly clearing the squares that are faded with 2+ light sources.  The square marked with the arrow should indeed be cleared (as well as the square above) with surrounding squares updated with the correct fade.

**Comment by islemaster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Minecraft: Allow two-corner illumination](https://trello.com/c/LzQ1Sywo/27-minecraft-allow-two-corner-illumination)
