### ISSUE TITLE
Tracks in the level config are mutated incorrectly by newly-placed tracks

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/craft#72]
Give this starting level config:

![screen shot 2017-09-01 at 3 14 56 pm](https://user-images.githubusercontent.com/413693/29989545-93e8f57e-8f28-11e7-9540-ecfc46ad8e54.png)

**Expected** — Placing a track should not mutate the corner track:

![screen shot 2017-09-01 at 3 15 03 pm](https://user-images.githubusercontent.com/413693/29989553-9e8166b0-8f28-11e7-9c2b-28cd1be18ba8.png)

**Actual** — This is what happens now:

![screen shot 2017-09-01 at 3 14 34 pm](https://user-images.githubusercontent.com/413693/29989554-a5b3197e-8f28-11e7-883e-37a2fc61d67f.png)

I think the issue is that LevelBlock tracks set by the initial config don't have `connectionA` and `connectionB` values filled in.

**Comment by WilliamHarmonMS** [comment]
no repro as of 10/6. I believe this was fixed and simply not closed.
