### ISSUE TITLE
Destroying any block causes incorrect Agent animation

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#79]
***Bug has been update to state that this occurs with most (if not all) blocks and not just Redstone***

Found at: https://code-dot-org.github.io/craft/

Destroying any block (old: Redstone Wire) causes the Agent to perform an infinite "boink" animation in which the Agent faces to the left (regardless of the direction of the destroyed Redstone wire) with the 3 impact lines as if he is continually running into a wall.

Steps:
1. Place any block (old: redstoneWire)
2. Destory the block with the Agent
3. Observe Agent animation

Attachment:
[HoC_DestroyRedstoneWire_IncorrectAgentAnimation.zip](https://github.com/code-dot-org/craft/files/1282998/HoC_DestroyRedstoneWire_IncorrectAgentAnimation.zip)

**Comment by v-samtha** [comment]
Bug has been update to state that this occurs with most (if not all) blocks and not just Redstone

**Comment by Hamms** [comment]
I believe this was fixed by https://github.com/code-dot-org/craft/pull/229; @v-samtha can you confirm that you are no longer seeing this behavior?

**Comment by joshlory** [comment]
I no longer repro.  Closing as fixed.
