### ISSUE TITLE
Destroying Redstone Wire displays gray particle animation

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#80]
Found at: https://code-dot-org.github.io/craft/

Destroying Redstone Wire causes a gray particle animation to occur instead of something red/black to better fit with the color of the wire.

Steps:
1. Place redstoneWire
2. Destory redstoreWire
3. Observe destruction animation

Attachment:
[HoC_DestroyRedstoneWire_GrayParticleAnimation.zip](https://github.com/code-dot-org/craft/files/1283005/HoC_DestroyRedstoneWire_GrayParticleAnimation.zip)

**Comment by joshlory** [comment]
Good find!  This should be an easy fix.  We'll just need to add an entry here:

https://github.com/code-dot-org/craft/blob/b5cf50e861a1fe135eec68b86334fcaeb373651a/src/js/game/LevelMVC/LevelView.js#L944-L951

**Comment by joshlory** [comment]
We should also update the destroying wire and tracks to happen instantly, without the Destroy_Overlay.png:

![image](https://user-images.githubusercontent.com/413693/30401065-d13c1c8a-988d-11e7-876a-1a23edd10618.png)
