### ISSUE TITLE
Destroying Rail does not cause it to drop to the ground

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#81]
Found at: https://code-dot-org.github.io/craft/

Destroying a Rail does not cause a sprite of it to drop to the ground and be picked up by the Agent.

Steps:
1. Place Rails
2. Destory Rails
3. Observe item drop (or lack thereof)

Attachment:
[HoC_DestoryRail_RailIsNotDropped.zip](https://github.com/code-dot-org/craft/files/1283008/HoC_DestoryRail_RailIsNotDropped.zip)

**Comment by joshlory** [comment]
Thanks for the bug report!  I think we'll need miniblock assets in order to implement the rail drop.
