### ISSUE TITLE
Powering Redstone Wires does not have a length limit

### ISSUE THREAD

**Issue by v-samtha** [code-dot-org/craft#82]
Found at: https://code-dot-org.github.io/craft/

When powering a Redstone Wire with a Pressure Plate, all of the connected Redstone Wire is powered. In comparison to the actual Minecraft game, Redstone Wires can transmit up to 15 blocks before petering out. (https://minecraft.gamepedia.com/Redstone#Redstone_component)

Steps:
1. Place a 15+ block long chain of Redstone Wire
2. Connect it to the Pressure Plate
3. Step on the Pressure Plate to give the Redstone Wire power
4. Observe length of power given to the Redstone Wire

Attachment:
![hoc_redstonewire_powersgreaterthan15blocks](https://user-images.githubusercontent.com/31709758/30139555-7d2851f0-9323-11e7-8437-28a8ca8069c4.png)

**Comment by joshlory** [comment]
I believe this is by design for the Hour of Code game.  Cole to confirm / deny.

**Comment by alalb** [comment]
I confirmed this with Cole. We don't need to worry about the limit.

**Comment by WilliamHarmonMS** [comment]
By design
