### ISSUE TITLE
Agent turns to face downward after placing a block or moving

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#86]
Found at: https://code-dot-org.github.io/craft/
If the player idles for a few seconds after moving the agent or having the agent place a block, the agent turns to face downwards on screen.  However, the agent's active facing direction has not actually changed, as placing or destroying a block still targets the direction the agent was facing before the turn to face downwards.  Idling after destroying a block does not cause the agent to turn.

1. Move (or place a block) in any direction other than down
2. Wait for a few seconds
3. Observe

Actual result: Agent turns
Expected result: Agent does not turn

[video.zip](https://github.com/code-dot-org/craft/files/1285813/video.zip)

**Comment by joshlory** [comment]
I think this was the behavior from the original 2015 Hour of Code?  We'll need to see if this change affects those levels.  Either way we should fix this!  Right now it's confusing because it looks like the character has changed orientation when really they haven't.

**Comment by joshlory** [comment]
It looks like @Hamms fixed this in PR https://github.com/code-dot-org/craft/pull/135.  Thanks Elijah!
