### ISSUE TITLE
Inconsistent behavior of white outline cursor when agent places and destroys blocks

### ISSUE THREAD

**Issue by v-chyou** [code-dot-org/craft#89]
Found at: https://code-dot-org.github.io/craft/
When the agent places a block, the white outline cursor moves to where the block was placed and remains there. However, when the agent destroys a block, the white outline cursor moves to the block being destroyed and then returns to the agent's location.

1. Destroy a block
2. Observe white outline
3. Place a block
4. Observe white cursor outline

Actual result: Inconsistent behavior of white outline cursor
Expected result: Consistent behavior of white outline cursor
[video.zip](https://github.com/code-dot-org/craft/files/1286187/video.zip)

**Comment by joshlory** [comment]
From @alalb:
> Cole suggest that we remove white square from the Agent and keep it for the player

**Comment by joshlory** [comment]
Currently the `Selection_Indicator.png` square also swaps between the Player and Agent, depending on who is moving.
